<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add New Event</name>
   <tag></tag>
   <elementGuidId>938cba08-a5c7-4652-b867-baee5740b9e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='addButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>851a91cd-d71c-44a5-8615-a7b2dcf7c1c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>calendar_content_addEvent</value>
      <webElementGuid>317aaf9b-8c76-4453-b7ea-4a04484cbce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addButton</value>
      <webElementGuid>b52e55d3-6e72-44a0-a647-69d6576f3912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>25ef7bed-c0f5-4742-8234-38d17aa44bc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>addNewTaskEvent('2','24-01-2024','-1','','v10Widget');</value>
      <webElementGuid>0927c1dd-a66d-4713-b668-f9e83160f06b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add New Event </value>
      <webElementGuid>9681a36c-9f6e-4fe8-b40a-6cd0de011801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addButton&quot;)</value>
      <webElementGuid>372c6393-42c5-43ae-a11e-d81e5749114e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboard/Event_Task/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>fb2a6c38-e645-47c5-933e-6cf7decd7519</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='addButton']</value>
      <webElementGuid>1f81ab0c-67b7-4c1a-a81e-a8cdaf93a78c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='calendar_content']/div/a</value>
      <webElementGuid>76e1a33b-b4fb-41eb-9425-e2d8f6ed4f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add New Event')]</value>
      <webElementGuid>4d6c736d-6f15-437a-aa27-816ea9cc91cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='January, 2024'])[1]/following::a[4]</value>
      <webElementGuid>004f923e-48ae-4bf4-8863-0734b6e0c1e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You have been credited (Casual Leave) by Testbits Training'])[1]/following::a[6]</value>
      <webElementGuid>c7850835-bd59-4bb8-a633-4fe8a2afa897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select employees:'])[1]/preceding::a[1]</value>
      <webElementGuid>96ea5d70-9138-4b8c-a3ad-cc07860a9e4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go'])[1]/preceding::a[3]</value>
      <webElementGuid>e1e1995f-a50d-46b5-bf76-96ab8622c501</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[8]</value>
      <webElementGuid>5ffa66e9-1ef8-450e-ac68-e188a13a4c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/a</value>
      <webElementGuid>d06a0225-797c-410e-b7b4-ccc011a65f30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'addButton' and @href = '#' and (text() = 'Add New Event ' or . = 'Add New Event ')]</value>
      <webElementGuid>49c956e3-772d-47b7-a55f-cb7c6e76d7b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
