<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Dashboards</name>
   <tag></tag>
   <elementGuidId>4591337f-3591-4d6d-8aec-1d0ac1db14fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#home</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='home']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4ec7469b-4b52-4666-878c-2ba32735b719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>home</value>
      <webElementGuid>8ea78d52-bdf5-43fe-b5c2-75f23664ddb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v10-side-menu-item sel-parent</value>
      <webElementGuid>b1697a2f-d2ea-468b-b0ab-40986dd4c694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>displayURL('runet.do?activity=submit&amp;mod=homePageContent');return false;</value>
      <webElementGuid>5440b68c-c0dc-40a3-8fd1-662532794718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboards</value>
      <webElementGuid>87a3a55f-dd39-438a-a8c7-b937c0cae64c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home&quot;)</value>
      <webElementGuid>bcaef7b6-a99e-4ce7-8d0f-5e9ebbbf3b3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='home']</value>
      <webElementGuid>ec775608-7cda-4120-999e-088154917871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='left_side_menus']/div/div</value>
      <webElementGuid>845af877-b68b-4cc4-9fae-2a0e803a5eeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log off'])[1]/following::div[5]</value>
      <webElementGuid>2b54f363-9a37-40b8-bc08-314edb0ec687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Self services'])[1]/preceding::div[4]</value>
      <webElementGuid>b7606d90-1646-4b51-b5bd-1577bc4e1963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div</value>
      <webElementGuid>56008398-2d43-4fd9-9993-c1038ef381f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'home' and (text() = 'Dashboards' or . = 'Dashboards')]</value>
      <webElementGuid>577f166a-cf15-4074-a242-ca079998bbc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
