<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Confirmation</name>
   <tag></tag>
   <elementGuidId>0bd67954-5303-4355-a53c-51222b6dcb78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ed7bbefb-3114-4bc9-b5df-455e3fbbe607_title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;84b5604c-6b4a-400e-823f-17495547a2c2&quot;]/div/div/div[1]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>96108226-1e6d-4905-ae9a-48e01b390227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bootstrap-dialog-title</value>
      <webElementGuid>9e9ce936-9eb7-4e69-87b9-ab5eaa268851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ed7bbefb-3114-4bc9-b5df-455e3fbbe607_title</value>
      <webElementGuid>a8fd07a3-42bc-42b2-97c9-ef26e27cc674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirmation!</value>
      <webElementGuid>7c14d3ca-b4c0-4145-b703-f61556242cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ed7bbefb-3114-4bc9-b5df-455e3fbbe607_title&quot;)</value>
      <webElementGuid>fd6fbf4d-18ad-4a1c-a126-8c18df641144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboard/Event_Task/Page_Home page/iframe_Self services_homePageFrame (3)</value>
      <webElementGuid>0031dfd9-0b13-41d6-8b90-31e26027daa0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ed7bbefb-3114-4bc9-b5df-455e3fbbe607_title']</value>
      <webElementGuid>e19743de-e18e-4de8-b96c-18188484e352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ed7bbefb-3114-4bc9-b5df-455e3fbbe607']/div/div/div/div/div[2]</value>
      <webElementGuid>ae2bb7f3-1927-4bd1-a68b-c5e28b88878a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[4]/following::div[1]</value>
      <webElementGuid>3fc7133b-1cb3-40dc-8af2-df982e92337a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::div[11]</value>
      <webElementGuid>116c935d-32f5-41ae-a0c8-6845b432ff45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Task has been saved successfully.'])[1]/preceding::div[1]</value>
      <webElementGuid>188b7b26-cba2-40b4-b3e4-13a8dd676ec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ok'])[1]/preceding::div[4]</value>
      <webElementGuid>0ba45c3d-d12e-4687-b961-042895eb38c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Confirmation!']/parent::*</value>
      <webElementGuid>0a3cbe75-d3fd-4029-86ba-d10ec8a3b717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/div/div[2]</value>
      <webElementGuid>4bd0ed5c-a312-4306-9b43-484b03802b50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ed7bbefb-3114-4bc9-b5df-455e3fbbe607_title' and (text() = 'Confirmation!' or . = 'Confirmation!')]</value>
      <webElementGuid>7f7e90ae-fce3-47d6-affa-fe1bdafb5f20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
