<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Press ALT 0 for help_cke_wysiwyg_frame cke_reset</name>
   <tag></tag>
   <elementGuidId>09e05956-dbab-4007-8ffb-908c74c206b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe.cke_wysiwyg_frame.cke_reset</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cke_155_contents']/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>1fc23fe9-7a88-4ebd-b717-d4c36f10732d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>39fe25bb-f182-45f0-8b43-f34997114f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cke_wysiwyg_frame cke_reset</value>
      <webElementGuid>68af724f-0fe8-4632-85fc-a2d6e0b3e1fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Rich Text Editor, ckEditor_description</value>
      <webElementGuid>dae0b56e-359c-4e9a-b03a-5f0428aa1cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>cke_184</value>
      <webElementGuid>4f58dfa4-0eb6-436f-8ba5-283f07cd7dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a8a25219-0811-418e-8f47-27f3df9b527e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b6b2d80e-e1dd-45a2-ade1-050942c2a25c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cke_155_contents&quot;)/iframe[@class=&quot;cke_wysiwyg_frame cke_reset&quot;]</value>
      <webElementGuid>89107d10-2476-41d3-b0a6-3b37ce1f6f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboard/Event_Task/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>a2b6483c-e6a1-47c3-af42-c363f8dcc187</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cke_155_contents']/iframe</value>
      <webElementGuid>3d263e28-063a-4da8-8d1d-f89dfadeb869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>c72103dd-21e6-417a-9a4e-650463422fed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'Rich Text Editor, ckEditor_description']</value>
      <webElementGuid>0d96e246-d3f0-4c56-9194-b1f154749db8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
