<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Private_isPrivateEvent</name>
   <tag></tag>
   <elementGuidId>d73f40dd-5040-445f-9019-b3d6d1cf6560</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isPrivateEvent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='isPrivateEvent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>725955aa-9a2a-434a-bf30-a9353421f393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>12b05b78-d090-42d5-9fdd-76703178b471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isPrivateEvent</value>
      <webElementGuid>1d139fe4-6ec4-4832-8607-dc452b3c8b1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isPrivateEvent&quot;)</value>
      <webElementGuid>71423914-27d7-467e-9b46-535919bfcc0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboard/Event_Task/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>3a3ac620-b11b-4aa0-9d83-f0bc01a71646</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='isPrivateEvent']</value>
      <webElementGuid>24b9fc0f-ca8e-4fb3-9504-ab8d1e9d45cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eventSection']/div[4]/div[2]/input</value>
      <webElementGuid>55a182d8-109b-4ee8-b262-f30ad39ce051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>4007fd63-764f-453f-90e7-e4568404f868</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'isPrivateEvent']</value>
      <webElementGuid>28aa8b3d-3d50-47b0-89ae-17bb6aaff5ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
