<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_All day event_allDayEventMode</name>
   <tag></tag>
   <elementGuidId>14d0beea-5a45-4a02-8797-fb8888dda04d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#allDayEventMode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='allDayEventMode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c8582c99-f8b5-4ff9-8c30-06fd003db623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e324c084-1d93-431f-9e68-c57b3c561f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>allDayEventMode</value>
      <webElementGuid>14cf2eb7-09ec-448c-8f5b-8c3b551c5d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>enableDisableTimeDurationBox(this);</value>
      <webElementGuid>c0871f42-7704-4718-8bc2-cf0282fa6247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;allDayEventMode&quot;)</value>
      <webElementGuid>e4346752-69a8-40b1-ae40-54e9090a5b5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboard/Event_Task/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>6f109e25-0316-4ed3-93da-b0015da50db5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='allDayEventMode']</value>
      <webElementGuid>d5116520-2997-4f4f-a813-42eb7eb5f1cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='allDayEventDiv']/input</value>
      <webElementGuid>a59026eb-6ba8-4121-8de1-b2758c3ed472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[4]/div/input</value>
      <webElementGuid>14c2b306-f377-4376-9890-718dd02b0689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'allDayEventMode']</value>
      <webElementGuid>91dafde5-aafc-434b-ab8c-10027886924e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
