<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Start time_startTime</name>
   <tag></tag>
   <elementGuidId>1a51439f-11d6-49c2-9f92-11619c3e4a67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#startTime</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='startTime']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b9e51f1b-780c-4501-b8cf-709ad46ae25c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bcb844ef-0aee-4851-b72a-1ad4b50cb1d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>233d8556-277e-459a-b233-dcc499520c53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>startTime</value>
      <webElementGuid>13c8621f-6cf6-4f0c-ba00-16db35f79d06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2e76ed83-e5b4-4dc2-bc89-ed3e2fbdfeea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>javaScript:displayTimeSlot(this.id);return false;</value>
      <webElementGuid>1cde84d6-14b7-4dc1-a5ad-b0e061410503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>validateHhMm(this);</value>
      <webElementGuid>461078de-b4c6-4fd9-9ac7-5c42b215631b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;startTime&quot;)</value>
      <webElementGuid>3db7be22-5bf3-4feb-9d26-595fdbfec2c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboard/Event_Task/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>b6794f82-caf8-4ac6-8c13-dcc33052542d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='startTime']</value>
      <webElementGuid>ac8ef1c2-8917-4ee7-b390-f2dd3faed13e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eventSection']/div[8]/div/input</value>
      <webElementGuid>5534cb17-78e7-46eb-9c70-4675088153e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[8]/div/input</value>
      <webElementGuid>adde9848-37d6-4557-9618-08da642a2fe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'startTime']</value>
      <webElementGuid>0b471356-d58f-487e-a28c-2794d977de46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
