<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Due on_date_selectedEndDate</name>
   <tag></tag>
   <elementGuidId>1ce20002-ab3a-4b4d-991a-88174beadaf4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selectedEndDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='selectedEndDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce67bec4-89b7-4aa2-b550-9880b2ef834d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>022e19c8-0908-47db-8a27-8a7a3b6c528e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectedEndDate</value>
      <webElementGuid>bc792a25-6150-4130-a756-0974d385f448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>date_selectedEndDate</value>
      <webElementGuid>4721d607-6c14-43c4-8cd5-e618cc08cb7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control cal hasDatepicker</value>
      <webElementGuid>30bddfcb-2e5d-4196-9826-02bdb991146a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectedEndDate&quot;)</value>
      <webElementGuid>5fa09b95-6a77-4094-a07b-c6633a48e723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboard/Event_Task/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>0842a6be-15e7-4e46-b6d0-ddf0186c1642</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='selectedEndDate']</value>
      <webElementGuid>892e9cf5-4bdb-4e99-bde8-383f65794e32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eventSection']/div[2]/div/div/input</value>
      <webElementGuid>dfc0aff7-89a8-4ae4-9dbb-7f567a6ccda3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div[2]/div/div/input</value>
      <webElementGuid>f2364cd6-f04a-46fe-9538-ff72a1121249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'selectedEndDate' and @name = 'date_selectedEndDate']</value>
      <webElementGuid>fb5aa639-2494-4acd-a2de-947d8350daf5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
