<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Multi-day event_multiDayEvent</name>
   <tag></tag>
   <elementGuidId>edb7e589-091a-4ae8-9234-4c47fcc48c38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#multiDayEvent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='multiDayEvent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1e44d791-d99f-48bd-a934-f9f12fc428bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>68f48d25-d6cf-4f13-9c33-730d5a2291d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>multiDayEvent</value>
      <webElementGuid>ab5ccbf4-36b8-47f0-a3bd-83560438650b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>enableDisableDateTimeBox(this);</value>
      <webElementGuid>ca618742-2256-4acc-8f4f-4dabbe0ce71c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;multiDayEvent&quot;)</value>
      <webElementGuid>a8b6e1d9-63d6-4667-9879-779c426d052c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboard/Event_Task/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>9483a634-7b0e-42dd-a159-52d4e3beab63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='multiDayEvent']</value>
      <webElementGuid>b500e9ae-ea90-44a3-901f-dc1d67483b29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eventSection']/div[2]/div/input</value>
      <webElementGuid>f2b1a7ec-8bea-4bdf-a838-0815df05623c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/input</value>
      <webElementGuid>d927d478-dbe5-4205-ba24-e51b39b7b318</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'multiDayEvent']</value>
      <webElementGuid>87633780-d8dd-466f-84ed-13d276468da1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
