<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Repeat_isRecurring</name>
   <tag></tag>
   <elementGuidId>2fae7a90-4916-4d7c-9592-e966658e083d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isRecurring</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='isRecurring']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3e6eba1d-d87e-47fd-8bd1-02a6ebfe4e82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e3f31fa6-18b9-48fc-8c9d-0f95ec82d1ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isRecurring</value>
      <webElementGuid>2205e327-be9d-4246-8609-36016cab7028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>showHideRepeatSection(this);</value>
      <webElementGuid>675f94b9-4ec2-4ba1-9505-bcd560090027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isRecurring&quot;)</value>
      <webElementGuid>5a885cec-1dca-495e-ae1a-2b5d9ca3f17c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboard/Event_Task/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>12a7b198-5553-476c-947d-c6a7fa5451c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='isRecurring']</value>
      <webElementGuid>6f8e65b0-fdee-48f9-96f6-eece7a093317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='isRecurringDiv']/div/input</value>
      <webElementGuid>7ad84b47-a2f8-4f3c-81cb-96e803190671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div/input</value>
      <webElementGuid>2c2af2e0-229f-4fc3-9e82-f3f32162baf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'isRecurring']</value>
      <webElementGuid>a7a042e4-602d-40ee-b8ee-117221867a75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
