<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Agenda</name>
   <tag></tag>
   <elementGuidId>db1486c5-758a-4787-bf06-edc2f0dc4878</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu_Agenda > label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu_Agenda']/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>fd37b645-3816-41ca-8079-d3cb1d57db1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agenda</value>
      <webElementGuid>62e56e43-2dc9-42f5-a9f9-adb1e14fdc3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu_Agenda&quot;)/label[1]</value>
      <webElementGuid>651c141b-ff0a-4e92-be72-ef3b12ec2ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboard/Event_Task/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>055da5e6-3310-4594-91e2-883a3e8b87a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu_Agenda']/label</value>
      <webElementGuid>2b0d0c14-d4ec-4db1-8bd8-fefb1aa3892b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event'])[2]/following::label[1]</value>
      <webElementGuid>5e843f8c-c5e9-4033-ab87-93ad8d30eaab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Task'])[1]/following::label[2]</value>
      <webElementGuid>6801c21e-bc43-42f1-b1c5-4c43e4cc2c50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subject'])[1]/preceding::label[1]</value>
      <webElementGuid>92093f79-b440-4eb3-b41f-f1a4fc16ae02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Agenda']/parent::*</value>
      <webElementGuid>6262a2d9-5d68-4ff1-a9a6-1ff3553e0740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/label</value>
      <webElementGuid>74b2274d-8069-47fd-9357-b4f66fc9a5f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Agenda' or . = 'Agenda')]</value>
      <webElementGuid>9d0ea311-2b59-44b4-8165-85c8a9fbf427</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
