<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_TimeZone</name>
   <tag></tag>
   <elementGuidId>d0de8339-02f1-4eee-a8bf-2d2597311fd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#timeZone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='timeZone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>48ace698-f952-4e05-8b92-b79599d3bc48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>timeZone</value>
      <webElementGuid>463ddb87-620b-4fa8-a695-40a6a9d93ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d72e2233-38bb-4c9a-b3b5-ae17e844d547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>---Select---(GMT-08:00) Pacific Time (US &amp; Canada)(GMT-07:00) Mountain Time (US &amp; Canada)(GMT-06:00) Central Time (US &amp; Canada)(GMT-05:00) Eastern Time (US &amp; Canada)(GMT+04:00) Abu Dhabi, Muscat(GMT) Greenwhich Mean Time(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi</value>
      <webElementGuid>d01bb32c-36e0-4736-849c-262e34f822e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;timeZone&quot;)</value>
      <webElementGuid>da8503ea-5156-43b0-8668-963d1c7609c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboard/Event_Task/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>a269e145-67f5-47cd-a2ef-e24a0f780173</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='timeZone']</value>
      <webElementGuid>61a02dc7-7b4e-4b74-9fae-5ad24e5b8d55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eventSection']/div[13]/div/select</value>
      <webElementGuid>415cdedc-a05b-487c-b7c9-fdc285db4484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time zone'])[1]/following::select[1]</value>
      <webElementGuid>86b3b052-70bc-4f57-bcb8-3b0189fa191b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duration'])[1]/following::select[2]</value>
      <webElementGuid>b88daca0-fed9-4e33-a3f4-5f3604bbece6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Frequency'])[1]/preceding::select[1]</value>
      <webElementGuid>4c9d8a56-0400-476e-befa-1523338377e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/select</value>
      <webElementGuid>5e19adc4-ce00-4b2b-b6d5-6bcd8d00249d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'timeZone' and (text() = '---Select---(GMT-08:00) Pacific Time (US &amp; Canada)(GMT-07:00) Mountain Time (US &amp; Canada)(GMT-06:00) Central Time (US &amp; Canada)(GMT-05:00) Eastern Time (US &amp; Canada)(GMT+04:00) Abu Dhabi, Muscat(GMT) Greenwhich Mean Time(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi' or . = '---Select---(GMT-08:00) Pacific Time (US &amp; Canada)(GMT-07:00) Mountain Time (US &amp; Canada)(GMT-06:00) Central Time (US &amp; Canada)(GMT-05:00) Eastern Time (US &amp; Canada)(GMT+04:00) Abu Dhabi, Muscat(GMT) Greenwhich Mean Time(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi')]</value>
      <webElementGuid>a6609e67-b5b0-49bd-99a8-15fd71170c19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
