<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_duration</name>
   <tag></tag>
   <elementGuidId>9e10e460-6825-45dd-8020-959f01207aa4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#duration</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='duration']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cbf5c601-1ff8-46dc-a99e-c33b907acaab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>duration</value>
      <webElementGuid>bd8b980e-ad09-45dc-8113-c3b59131bdf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0dc88e4d-daaa-43d7-a588-8ec5691abbc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>---Select---15 Minutes30 Minutes45 Minutes1 Hour1 Hour 30 minutes2 Hour2 Hour 30 minutes3 Hour3 Hour 30 minutes4 Hour5 Hour6 Hour8 Hour</value>
      <webElementGuid>7eacafa4-b025-42c2-b7d7-ee14a39a5887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;duration&quot;)</value>
      <webElementGuid>51e5fe1f-827a-4d02-aa0d-4d9313cad394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboard/Event_Task/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>49bd0043-8f9e-4441-8e33-a205a02cd377</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='duration']</value>
      <webElementGuid>979b18b7-faa7-4034-8196-2d087fb8e4f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='durationDiv']/div/select</value>
      <webElementGuid>de492624-ab83-48bd-9e0f-83b0a9afbab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duration'])[1]/following::select[1]</value>
      <webElementGuid>e4d2fe99-c637-4310-bbb5-a78598576639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End time'])[1]/following::select[2]</value>
      <webElementGuid>d157da3c-7c0d-4579-854f-3d636dcd22b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time zone'])[1]/preceding::select[1]</value>
      <webElementGuid>d96ddb62-fce1-4a59-ab35-b25a01dfb5f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/select</value>
      <webElementGuid>e88822fa-3b58-4ce6-92d4-9264a0aed0cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'duration' and (text() = '---Select---15 Minutes30 Minutes45 Minutes1 Hour1 Hour 30 minutes2 Hour2 Hour 30 minutes3 Hour3 Hour 30 minutes4 Hour5 Hour6 Hour8 Hour' or . = '---Select---15 Minutes30 Minutes45 Minutes1 Hour1 Hour 30 minutes2 Hour2 Hour 30 minutes3 Hour3 Hour 30 minutes4 Hour5 Hour6 Hour8 Hour')]</value>
      <webElementGuid>0e22f22e-d6e2-4883-9b5a-44f7c82f4130</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
