<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AMPM</name>
   <tag></tag>
   <elementGuidId>0c9b817c-5b99-4ada-a8ce-44b4d0d749e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#startTime_ampmOptions</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='startTime_ampmOptions']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>92ffb0e4-0740-4b31-98e1-2c424550eacd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>startTime_ampmOptions</value>
      <webElementGuid>ef2213c9-421a-466e-bc04-bd868f0e8a66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ead3f162-aa56-4c2b-8f5a-99f7cd55879d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AMPM</value>
      <webElementGuid>3ac51005-6af0-473c-a1cb-4c71f4a9ed70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;startTime_ampmOptions&quot;)</value>
      <webElementGuid>a44529a3-f475-4bd5-8e36-ad4a3d40357a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboard/Event_Task/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>b38fcd43-2381-4bb8-96ff-00bf74e639d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='startTime_ampmOptions']</value>
      <webElementGuid>8b6de0f3-cd05-41fe-be21-9880e333be1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eventSection']/div[8]/div[2]/select</value>
      <webElementGuid>6ba004aa-0f3e-4367-aa1d-54306dfe5f03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start time'])[1]/following::select[1]</value>
      <webElementGuid>d1d43611-9849-4f7a-b697-5e4fa7dff0ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start date'])[1]/following::select[1]</value>
      <webElementGuid>ee9f5dff-ea29-465d-b66c-30e598506168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End date'])[1]/preceding::select[1]</value>
      <webElementGuid>f2de0af0-9b4f-4cd7-bda2-cc24fd9c4f7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End time'])[1]/preceding::select[1]</value>
      <webElementGuid>b1911d7a-7b8d-4d45-9241-35bc2412871d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/select</value>
      <webElementGuid>c1a2f86b-46bb-4d18-ba60-fa293a63ed67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'startTime_ampmOptions' and (text() = 'AMPM' or . = 'AMPM')]</value>
      <webElementGuid>c7f0ae27-4870-45fb-a335-3054ceec1e6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
