<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Good eveningemp,</name>
   <tag></tag>
   <elementGuidId>5cd4f70a-2946-404c-9dc7-37dec9f1ee54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.font_display_medium_bold.welcome-h1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='displayPageContent']/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aef7ee06-990e-45cb-ae2a-345d3c53dea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font_display_medium_bold welcome-h1</value>
      <webElementGuid>3344e434-c091-4aae-b108-5e58e8e707c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Good evening emp, </value>
      <webElementGuid>a6bd3c75-87aa-4fbc-86b7-f6ca99da8455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;displayPageContent&quot;)/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;v10-content-section&quot;]/div[@class=&quot;col-md-9 col-sm-12&quot;]/div[@class=&quot;font_display_medium_bold welcome-h1&quot;]</value>
      <webElementGuid>6d79a4cd-3a9c-45aa-84d6-5d0c3a0b6a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/empxtrack Account Login/Page_Empxtrack logon/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>a88b8871-6b18-4d72-ba50-a1aefc69863b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='displayPageContent']/div/div[2]/div/div</value>
      <webElementGuid>05bfdb53-8b1d-42b1-ab92-591fcbe3e82d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wed 24 Jan, 10:31 PM'])[1]/preceding::div[2]</value>
      <webElementGuid>3f5bffcf-9668-484a-9713-5ad894ef3f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div</value>
      <webElementGuid>8d4d6734-5754-45f1-ade1-3158252abbe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Good evening emp, ' or . = 'Good evening emp, ')]</value>
      <webElementGuid>fe7bae66-1a1d-4a49-bb62-1c3c7d208285</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
