<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Holiday Calendar</name>
   <tag></tag>
   <elementGuidId>82366d19-a747-4667-b53d-e499f66e19f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn_Holiday20Calendar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_Holiday20Calendar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>05edaae1-1924-47e6-bdd9-53b61cef34fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn_secondary</value>
      <webElementGuid>a227f959-e8b3-44ae-a3be-017006382547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_Holiday20Calendar</value>
      <webElementGuid>89506b4e-ae14-467b-9e0e-dad72e57ac90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>876968cd-f8f2-4a23-86c1-489f5a12ac12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:encryptURLForPanel('mod=MyLeaveDetails&amp;secondaryVar=extendedDwrMode^showHolidayCalendar');return false;</value>
      <webElementGuid>c2b1ff53-6107-4654-85a9-abd1e00088fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Holiday Calendar</value>
      <webElementGuid>b3698af6-e555-49f0-9298-9bd0033509c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_Holiday20Calendar&quot;)</value>
      <webElementGuid>0f64e930-407e-4cc5-a2b5-cf9aace3a33d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboard/Attendance/iframe__mycontent-right-frame</value>
      <webElementGuid>23aab6d1-b8d8-4fb1-be01-b6447cf32241</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn_Holiday20Calendar']</value>
      <webElementGuid>630788e3-e519-494c-bb54-7a41aad45efd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-section-panel']/div/div/div[3]/div/div/a[2]</value>
      <webElementGuid>811ca98c-2cef-427b-a9b0-65382eb344f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Holiday Calendar')]</value>
      <webElementGuid>deb58a5d-a9c1-474f-b5e6-971f4198c7a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply for leave'])[1]/following::a[1]</value>
      <webElementGuid>f64a5045-beba-4ce0-8d91-69594c93cb18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View in full page'])[1]/preceding::a[1]</value>
      <webElementGuid>1b8de89a-79d6-493f-85f3-2af053b0c716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[3]/preceding::a[2]</value>
      <webElementGuid>614a9a74-d94b-4e0b-a919-b746aa9b6954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Holiday Calendar']/parent::*</value>
      <webElementGuid>ca07c4a7-178a-468a-9b4b-e638eb4ac67f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[3]</value>
      <webElementGuid>8205b05e-e85f-49d4-9314-fd676457e39c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a[2]</value>
      <webElementGuid>8cd1e846-347d-437e-ae8d-cada2ca690a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btn_Holiday20Calendar' and @href = 'javascript:void(0);' and (text() = 'Holiday Calendar' or . = 'Holiday Calendar')]</value>
      <webElementGuid>4a471a8f-e843-4c48-8e1e-19fb42116b8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
