<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK</name>
   <tag></tag>
   <elementGuidId>1014d1a7-a9ab-4626-9221-3d2d78b60c75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure you want to mark the close of the day?'])[1]/following::button[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#23274071-55da-4117-9cc6-762b9a7f5dbb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>20893478-3753-48ce-981b-5aa11a6bb86c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>7f187990-0eec-4a6d-a7f7-ebdee4fff5c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>23274071-55da-4117-9cc6-762b9a7f5dbb</value>
      <webElementGuid>80adfa97-86df-48fd-9ac0-75e887a4dd2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>f0593217-7861-41e2-98ad-4ea37cf1f1a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;23274071-55da-4117-9cc6-762b9a7f5dbb&quot;)</value>
      <webElementGuid>2d8886f9-5518-4287-81b6-945c4f43cb78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboard/Attendance/iframe_Self services_homePageFrame</value>
      <webElementGuid>e088099c-a878-4015-ab6a-459892261076</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='23274071-55da-4117-9cc6-762b9a7f5dbb']</value>
      <webElementGuid>33b8489e-6609-465e-892b-9f67ba1e9c18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e5c16e8b-8436-42b5-a849-4358084ca880']/div/div/div[3]/div/div/button</value>
      <webElementGuid>ce247e8e-6c91-4839-9430-f8fb4399b7a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure you want to mark the close of the day?'])[1]/following::button[1]</value>
      <webElementGuid>faa18966-8384-495d-8788-b11107b37aff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmation message'])[1]/following::button[1]</value>
      <webElementGuid>31e5e0f4-27b9-4ea0-bfaa-97dfaaf27545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[1]</value>
      <webElementGuid>ef0ca195-45a8-418b-b5f1-ce9693ebddeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OK']/parent::*</value>
      <webElementGuid>0d1edf31-d045-40b4-99f2-436f28d2772e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>d804925a-a04b-4d9d-86cf-7a8726fc2996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '23274071-55da-4117-9cc6-762b9a7f5dbb' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>dc8b39ea-c46d-4930-b72d-bdf3ecdf87e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
