<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Apply for leaveHoliday CalendarView in full page</name>
   <tag></tag>
   <elementGuidId>374de7e3-d42a-4800-a2f7-1d7f10958725</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content-section-panel']/div/div/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.second-line</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1c11b774-b901-444f-81d5-e309431fed66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>second-line</value>
      <webElementGuid>6ad98b23-f3a8-4fce-a787-fc1e18af6c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apply for leave  Holiday Calendar  View in full page</value>
      <webElementGuid>dc346569-67ea-4e56-bd4d-a1aa0cb25019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-section-panel&quot;)/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;content-section&quot;]/div[@class=&quot;second-line-outer btn-panel-bottom-align-class&quot;]/div[@class=&quot;second-line&quot;]</value>
      <webElementGuid>32a9914a-68c1-4758-859c-a8fc54a8d0a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboard/Attendance/iframe__mycontent-right-frame</value>
      <webElementGuid>90028855-57fd-4a1b-94c6-a93aed77979b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-section-panel']/div/div/div[3]/div</value>
      <webElementGuid>06151c8b-6d99-4bdd-94f9-98da3b5f63d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[3]/div</value>
      <webElementGuid>9a5fbd20-6125-41b6-ac12-80a9268545f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Apply for leave  Holiday Calendar  View in full page' or . = 'Apply for leave  Holiday Calendar  View in full page')]</value>
      <webElementGuid>2d6963e9-0a62-4167-be3a-6083e8b400d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
