<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_view_full_screen_attendance</name>
   <tag></tag>
   <elementGuidId>5e559e5d-69c6-4a49-817e-bb91589e387c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='renderTipId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#renderTipId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cf219629-8510-4d27-a690-acfbe73d7a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>renderTipId</value>
      <webElementGuid>32101c0a-e854-45ee-8c63-472432689ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alert alert-help</value>
      <webElementGuid>8a9f5635-8e9d-470e-90a0-3c1aae24c0a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>You are viewing your attendance for the current month. Each day has a status that maps to the entries for the day. Click on any date to view details for the date. You can regularize the attendance for a current or past day, apply for leave or view the holiday calendar. Click on View details link in Effective days worked section to get a summary of attendance.</value>
      <webElementGuid>3dd0184d-e5fb-4239-91df-ab3fd1de42bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;renderTipId&quot;)</value>
      <webElementGuid>18ec906e-8a1c-4519-a3cc-bfa17a93d581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboard/Attendance/iframe_Self services_homePageFrame</value>
      <webElementGuid>ebb1a803-1399-4d23-95e2-f6a9bf8ebd35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='renderTipId']</value>
      <webElementGuid>aad5b942-17d7-47d8-996f-40190e79d817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='displayPageContent']/div[2]/div</value>
      <webElementGuid>d2d03c22-0e8c-428b-8cd8-b68fb7ad9ebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/following::div[5]</value>
      <webElementGuid>87ae2580-f95c-42c3-9d69-45766e6923cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attendance'])[1]/following::div[9]</value>
      <webElementGuid>af3d987d-38d2-4494-aac8-20d8b495c9ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This is the default assigned shift. To change the shift, regularize attendance for the day.'])[1]/preceding::div[8]</value>
      <webElementGuid>3766ab9c-2267-41d5-9240-621a7a5307de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='You are viewing your attendance for the current month. Each day has a status that maps to the entries for the day. Click on any date to view details for the date. You can regularize the attendance for a current or past day, apply for leave or view the holiday calendar. Click on View details link in Effective days worked section to get a summary of attendance.']/parent::*</value>
      <webElementGuid>31e5d2e3-9965-42f5-9805-6173a5eee110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div</value>
      <webElementGuid>0474515c-eb37-4c83-b107-0b8298b581bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'renderTipId' and (text() = 'You are viewing your attendance for the current month. Each day has a status that maps to the entries for the day. Click on any date to view details for the date. You can regularize the attendance for a current or past day, apply for leave or view the holiday calendar. Click on View details link in Effective days worked section to get a summary of attendance.' or . = 'You are viewing your attendance for the current month. Each day has a status that maps to the entries for the day. Click on any date to view details for the date. You can regularize the attendance for a current or past day, apply for leave or view the holiday calendar. Click on View details link in Effective days worked section to get a summary of attendance.')]</value>
      <webElementGuid>08651378-11f0-4938-9b39-ebf8f9c59c08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
