<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Create ticket</name>
   <tag></tag>
   <elementGuidId>c47e0981-42a4-4d84-ae82-6807cf2f9fb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='secondary_link_createTicket']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#secondary_link_createTicket</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d9d0e2e3-7612-49d9-90be-d25edd9a7d3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>f01f52de-1500-43d2-9207-9d3b414403a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>secondary_link_createTicket</value>
      <webElementGuid>e2a24e89-be4d-4c8b-8e25-49f26af6bb2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>encryptURLForPanel('runet.do?activity=submit&amp;mod=MyTicketHelpDesk&amp;secondaryVar=extendedDwrMode^createTicketRequest')</value>
      <webElementGuid>88e5152a-c623-43a8-8190-018f405fff9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-view</value>
      <webElementGuid>012e8ebd-fdad-4e5d-89b9-4dbc1d45a443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create ticket</value>
      <webElementGuid>849516d4-d85e-4981-b037-ec1177df0377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;secondary_link_createTicket&quot;)</value>
      <webElementGuid>2ccdb36d-3596-4d9d-8e94-181b6b61acae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/self_Service/Ticket/iframe_Self services_homePageFrame</value>
      <webElementGuid>8bd3b739-149a-4d63-8363-43685a0a079c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='secondary_link_createTicket']</value>
      <webElementGuid>4245700e-0658-4839-8047-4c00be23dd84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='showMyTicketsHelpDesk_getSecondaryLinks']/div[2]/a[2]</value>
      <webElementGuid>ab86edf2-574b-42e9-9da9-12c59c9a9f1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Create ticket')]</value>
      <webElementGuid>896274a3-d4fe-491c-a059-c1d135008c78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My tickets'])[1]/following::a[1]</value>
      <webElementGuid>718e1a4e-ce32-4bf9-8e9a-f785c8256af1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No records are available'])[2]/following::a[2]</value>
      <webElementGuid>d057303e-868a-4bcd-884d-c3f2bfe75e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver: 10.10.04'])[1]/preceding::a[2]</value>
      <webElementGuid>a7de7039-1dfc-49b1-b2fa-d836fbdf5910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms of services'])[1]/preceding::a[3]</value>
      <webElementGuid>0f37ffec-457a-4f92-a665-77a6d55f7043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create ticket']/parent::*</value>
      <webElementGuid>78149525-cfc9-4cf6-a2f0-b104ec652498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[10]</value>
      <webElementGuid>7cd4a996-7e21-4349-b452-9866fac5614b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div[4]/div[2]/a[2]</value>
      <webElementGuid>79ac100e-aeaa-4c7a-aeed-8807cdfe9a53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'secondary_link_createTicket' and (text() = 'Create ticket' or . = 'Create ticket')]</value>
      <webElementGuid>f068e2f7-e100-42a5-840e-fa3e73031c98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
