<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>body_html_description</name>
   <tag></tag>
   <elementGuidId>cb62971e-1b02-4d11-922a-49e1b15374b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>body.cke_editable.cke_editable_themed.cke_contents_ltr.cke_show_borders</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>body</value>
      <webElementGuid>f28dd195-b1bc-4121-9b35-60e9c827adf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b33255e6-6963-4cba-b55a-a4004e8e5e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cke_editable cke_editable_themed cke_contents_ltr cke_show_borders</value>
      <webElementGuid>c395db4f-98c9-47c6-b8ae-d07b190a5498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dfef2df0-ea69-41e4-a713-ed72a3e61f08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;cke_editable cke_editable_themed cke_contents_ltr cke_show_borders&quot;]</value>
      <webElementGuid>82cdb239-fd40-447c-abd0-23f4fb1f6c4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;cke_editable cke_editable_themed cke_contents_ltr cke_show_borders&quot;]</value>
      <webElementGuid>5489f0e2-0b4b-4a67-bb9b-9716f852f545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/self_Service/Ticket/iframe_Press ALT 0 for help_cke_wysiwyg_frame cke_reset</value>
      <webElementGuid>a25a0862-3566-4766-850b-3d55b8323b73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body</value>
      <webElementGuid>2d2d7412-cdb6-433e-ad43-26bde3f1d613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//body[(text() = '/html[1]/body[@class=&quot;cke_editable cke_editable_themed cke_contents_ltr cke_show_borders&quot;]' or . = '/html[1]/body[@class=&quot;cke_editable cke_editable_themed cke_contents_ltr cke_show_borders&quot;]')]</value>
      <webElementGuid>e1f3bc3b-5bab-4268-86db-fba4e4bc2147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//iframe[@id='mycontent-right-frame']</value>
      <webElementGuid>12742650-723b-420e-8897-f2a3d82ad2a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//iframe[@title='Rich Text Editor, ckEditor_description']</value>
      <webElementGuid>185189c3-29c3-460d-870a-d975af443f5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
