<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK</name>
   <tag></tag>
   <elementGuidId>af400aa0-8b7b-4987-af82-6e1328b60f96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#8b8eda01-19f7-42cd-99ec-cfe5bb31ec3d</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7a161aec-3995-4365-9702-e7ead7ae13ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>9964702b-c463-4821-b060-40074f06e44e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>8b8eda01-19f7-42cd-99ec-cfe5bb31ec3d</value>
      <webElementGuid>ad4d86bb-d994-4d56-9252-ea5544e761c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>dcebaa51-ec76-4704-9eac-6cd9cba1f6f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;8b8eda01-19f7-42cd-99ec-cfe5bb31ec3d&quot;)</value>
      <webElementGuid>17c2823c-5fca-4829-8cf4-d3e7be26f782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/self_Service/Ticket/iframe__mycontent-right-frame</value>
      <webElementGuid>b6e46ce4-ff8f-4ae2-8e29-e15e2f943fd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='8b8eda01-19f7-42cd-99ec-cfe5bb31ec3d']</value>
      <webElementGuid>ff445d24-935c-46f5-92d3-b0516dc5a0d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c1b7ff91-ba16-45c7-ae7c-dbda00f6271a']/div/div/div[3]/div/div/button</value>
      <webElementGuid>dfb99493-53ba-4876-8b89-8b1ddbb4e656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select the ticket type.'])[1]/following::button[1]</value>
      <webElementGuid>ff276a23-ac29-4a35-bf5b-eebc22399394</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/following::button[1]</value>
      <webElementGuid>7fc76505-4620-4a09-8c75-f0686a4cc573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OK']/parent::*</value>
      <webElementGuid>e8754d9d-9398-4236-b8a2-25d41628af34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>67175398-9682-4740-9e95-b4e6482f5a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '8b8eda01-19f7-42cd-99ec-cfe5bb31ec3d' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>33bbecfc-d845-453b-9ce1-6c3a9a08cbaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
