<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Self services_homePageFrame</name>
   <tag></tag>
   <elementGuidId>b6ff1bff-725c-481d-903f-8de7acfd036c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='homePageFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#homePageFrame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>7cc66601-3231-43d1-83b6-994c29805524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>runet.do?activity=submit&amp;enc=GWVNfPq8cZnGsvK1Xva4QwNi5YpOlAOdHumu3zWooNKn6q+4FkL3YHBTv%2FoBPkQCSKAEwXJYPPjf8hw0irmnGYd4MVZRb2B1qRN8AqHWcWzc0Vk2VYrBXFrflQK6wcWmfFCpYlj91csFmIljl8ffI3gN%2FGZMtIfx1UpoEgpdF+ohKNKm4v+9i0g1IPevqMVYl70ffC+%2FIZ5nviNNy8jKC9Gt9KJW0toHClFVQJBlXDQ%3D</value>
      <webElementGuid>1bb9cf99-54b9-40f4-be9f-4a147088b7ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>homePageFrame</value>
      <webElementGuid>bd86437c-3795-4de2-b2cd-8b9daf6f784c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>overlay_homePageFrame</value>
      <webElementGuid>9f90d340-aa02-4019-98dc-7c6269a2233f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>homePageFrame</value>
      <webElementGuid>9cc36c44-2957-4d86-8938-c932777a0770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;homePageFrame&quot;)</value>
      <webElementGuid>5cceee50-fbd3-4f1e-9a8f-1853edf1f845</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='homePageFrame']</value>
      <webElementGuid>72efe210-08d0-41a0-bc80-93a115ab0df0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-section']/iframe</value>
      <webElementGuid>22f9d802-a79e-456f-b0f4-c63dfe4b04cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>4de9c024-6556-4a5f-969d-6763f5576712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'runet.do?activity=submit&amp;enc=GWVNfPq8cZnGsvK1Xva4QwNi5YpOlAOdHumu3zWooNKn6q+4FkL3YHBTv%2FoBPkQCSKAEwXJYPPjf8hw0irmnGYd4MVZRb2B1qRN8AqHWcWzc0Vk2VYrBXFrflQK6wcWmfFCpYlj91csFmIljl8ffI3gN%2FGZMtIfx1UpoEgpdF+ohKNKm4v+9i0g1IPevqMVYl70ffC+%2FIZ5nviNNy8jKC9Gt9KJW0toHClFVQJBlXDQ%3D' and @id = 'homePageFrame' and @name = 'homePageFrame']</value>
      <webElementGuid>bb10ccca-dfac-45de-b3c6-dfc38942d5c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
