<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__mycontent-right-frame</name>
   <tag></tag>
   <elementGuidId>cbc32de8-6a94-4484-9c8e-3524f770bf21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='mycontent-right-frame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mycontent-right-frame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>752488dc-a057-4a4a-9bf0-fd3419c4ea84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05Ulig4GmGZIiHumu3zWooNIXh0WR9DlEEf4QQkbh1kTq8EEjGSGIgp93NLybrSpZx1RDWoQwnpFVGW6D58K%2FzdIxXugOrMShYDVLGBJLXKy6XN1HRf9YWA8+p66Tu4GKIgwrPi1xWTAO8MnGjZmVrUH5Ls4C4O7dtZf%2F3ew3pEmTjEX3jwwjAKQ9MZlInmbshqyYONdAlNLQUOIX5sClQ63uXxtS7H6uWOXoJFPuif8Gpgid9mlbpqiEYjZ9c2MgFe7F+Vqde4Et&amp;cdmtHeaderBar=false&amp;showInPanel=true</value>
      <webElementGuid>bd34138f-020f-4700-827c-cfb00701c5eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mycontent-right-frame</value>
      <webElementGuid>08b6fb36-047d-490e-a145-57eff5ff2af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mycontent-right-frame</value>
      <webElementGuid>95e93426-db36-4e27-bbe6-b09e6b0b56d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mycontent-right-frame</value>
      <webElementGuid>b5749825-a943-47e1-8901-24dfd15b2e21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>28b571c6-78d3-43c8-b018-a6935d8ba9ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>95%</value>
      <webElementGuid>7798d2f8-5323-4104-b159-fe1fd15a2842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mycontent-right-frame&quot;)</value>
      <webElementGuid>1ebaa3d9-bcdf-473d-98ad-2c9222b62694</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='mycontent-right-frame']</value>
      <webElementGuid>8da6919a-abcf-44f3-97ea-9f27f8e4df93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mycontent-right']/iframe</value>
      <webElementGuid>f14c4365-372e-46bd-ac96-97a00f7f2cbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/iframe</value>
      <webElementGuid>150ec335-7fa2-4991-8eee-d4b1e2bef61b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05Ulig4GmGZIiHumu3zWooNIXh0WR9DlEEf4QQkbh1kTq8EEjGSGIgp93NLybrSpZx1RDWoQwnpFVGW6D58K%2FzdIxXugOrMShYDVLGBJLXKy6XN1HRf9YWA8+p66Tu4GKIgwrPi1xWTAO8MnGjZmVrUH5Ls4C4O7dtZf%2F3ew3pEmTjEX3jwwjAKQ9MZlInmbshqyYONdAlNLQUOIX5sClQ63uXxtS7H6uWOXoJFPuif8Gpgid9mlbpqiEYjZ9c2MgFe7F+Vqde4Et&amp;cdmtHeaderBar=false&amp;showInPanel=true' and @id = 'mycontent-right-frame' and @name = 'mycontent-right-frame']</value>
      <webElementGuid>a54f79b6-71ec-4981-8f3b-1a82ef2fd57c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
