<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_like</name>
   <tag></tag>
   <elementGuidId>a6ac0b5e-6832-4dfd-8071-73fef929d409</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='fontCls_1000012']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fontCls_1000012</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a41d7c57-7c38-46a9-91f6-ec5855074a9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fontCls_1000012</value>
      <webElementGuid>60f296f5-f117-4855-9bdd-50cace3125f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>far fa-thumbs-up likefeed</value>
      <webElementGuid>f86b982c-cb4c-4890-9ba5-3b117a624ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fontCls_1000012&quot;)</value>
      <webElementGuid>cd921bb1-b859-4a64-81a1-8c33b3418639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboard/Feed/iframe_Self services_homePageFrame</value>
      <webElementGuid>08767bac-2e59-4c76-97bf-2be7b2846569</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='fontCls_1000012']</value>
      <webElementGuid>bd37d1bb-0d68-4040-8225-975d37f3d64a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='jsFunUpdate_1000012']/i</value>
      <webElementGuid>7ed48bc8-4800-444f-b6ac-25a44f242878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/a/i</value>
      <webElementGuid>d32766b5-1d5a-4e95-807f-a194118dcdd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'fontCls_1000012']</value>
      <webElementGuid>615f3f50-2057-4694-af9d-6e10be8404f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
