<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_comment</name>
   <tag></tag>
   <elementGuidId>a869468b-064d-44df-8958-9098c119bf97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_reponse_note_1000012']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#_reponse_note_1000012</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fe9eac9a-4250-4ab8-aebb-39291c9f2f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4205726c-4549-4a69-94df-ff46e2c3a658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_reponse_note_1000012</value>
      <webElementGuid>43cc4f0b-fc9d-4e56-bd64-c5c68ac0a5bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e8c080ca-50a4-4df4-a4e9-b4bdbef6b6c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your comment</value>
      <webElementGuid>d7bd560a-9fe7-4b95-9022-aa1f94ec7b15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_reponse_note_1000012&quot;)</value>
      <webElementGuid>e7413a06-e96a-4bc6-87f3-f00272d82299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboard/Feed/iframe_Self services_homePageFrame</value>
      <webElementGuid>a2988715-664f-426e-bc73-aeaab6a7ac35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_reponse_note_1000012']</value>
      <webElementGuid>8d6d3cd3-6891-45e0-adba-1492c3bac21c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='buddy_box_1000012']/div[8]/div/div/input</value>
      <webElementGuid>bee964e5-285a-475c-8343-768829b5642d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/input</value>
      <webElementGuid>a42cccaa-1c15-4f48-9ecf-a6f0b4f09104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = '_reponse_note_1000012' and @placeholder = 'Enter your comment']</value>
      <webElementGuid>b42c3389-6ea0-45b4-9550-0db272ca43cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
