<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_exctied_emoji</name>
   <tag></tag>
   <elementGuidId>5cfb0960-2360-4ace-b84f-271b60c67813</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='help-header_1000012']/div/div[19]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;SMILING FACE WITH OPEN MOUTH AND TIGHTLY-CLOSED EYES&quot;] > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fbd14904-932a-4b08-97ec-e3c0915afce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>😆</value>
      <webElementGuid>bc9defb6-81f6-4488-b5fb-439a7264c16e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;help-header_1000012&quot;)/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;col-md-2&quot;]/a[1]/span[1]</value>
      <webElementGuid>2b4a34e9-e1f3-4be5-aea2-36742d514aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboard/Feed/iframe_Self services_homePageFrame</value>
      <webElementGuid>d5a1e7d6-df87-4ad4-8614-5803a5da3e49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='help-header_1000012']/div/div[19]/a/span</value>
      <webElementGuid>d50691e8-ad71-425f-bfd3-4452467e47ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='😅'])[1]/following::span[1]</value>
      <webElementGuid>1edef0f8-09b7-401e-bec6-a2d147db88f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='😄'])[1]/following::span[2]</value>
      <webElementGuid>68b31031-f5f2-49d8-bccd-27f4fe7484e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='😇'])[1]/preceding::span[1]</value>
      <webElementGuid>3617bfa5-3b04-4a32-b03d-2ee1775dc256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='😈'])[1]/preceding::span[2]</value>
      <webElementGuid>87084a39-215f-4f82-86be-d4e365627aac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='😆']/parent::*</value>
      <webElementGuid>30e0d858-b8e9-46dd-aa8b-621ef27a14ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/a/span</value>
      <webElementGuid>a2090b6a-e8bb-42dc-9ace-d2d46533a6a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '😆' or . = '😆')]</value>
      <webElementGuid>48c390b0-a55c-479a-bb87-9c14140de605</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
