<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK</name>
   <tag></tag>
   <elementGuidId>311b5290-b28d-4f22-b9ff-d22264eed796</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/following::button[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#603cb95f-2895-430a-bdad-ba3c8d21aff1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c0cc9dea-d7bd-4c7e-9b00-64cf45f1e5b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>f3022fff-5193-4980-90b1-595b226e0f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>603cb95f-2895-430a-bdad-ba3c8d21aff1</value>
      <webElementGuid>79cb659a-041e-4a75-a78c-3804055b2186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>52ef2bab-a2d3-47c9-ad01-02b148cb39f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;603cb95f-2895-430a-bdad-ba3c8d21aff1&quot;)</value>
      <webElementGuid>2a2aec2d-d84e-48e1-b8f5-7080ebe78742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboard/Leave/iframe_Self services_homePageFrame</value>
      <webElementGuid>bb5074cc-b71b-4a9b-8a7a-344b04d3cbd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='603cb95f-2895-430a-bdad-ba3c8d21aff1']</value>
      <webElementGuid>4f950078-6668-4fad-a9ac-79dac33f5a28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='59aa99b9-823f-4f94-bb72-0a463d6b4f66']/div/div/div[3]/div/div/button</value>
      <webElementGuid>6cebca25-448b-4d6a-94d8-f44ce1076eae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/following::button[1]</value>
      <webElementGuid>681f537f-559d-4295-b324-abe268b74f5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[4]/following::button[1]</value>
      <webElementGuid>69796bfa-11df-41cc-92f6-f77a71804852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OK']/parent::*</value>
      <webElementGuid>1611bb03-99ab-4d5f-b4b3-02089d1eff65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>4dfed99f-548a-47b0-bc93-224cb16d39d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '603cb95f-2895-430a-bdad-ba3c8d21aff1' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>1beb1c9d-1714-4078-ba02-65cb7458e04b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
