<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Apply_fa fa-arrow-circle-right</name>
   <tag></tag>
   <elementGuidId>b5eb3101-6147-450b-8ee0-f5ca43a01ee3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//i[@ref_element = 'Object Repository/Leave/iframe_Self services_homePageFrame']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-arrow-circle-right</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>c88e9da8-bf9a-4ce8-aca2-05b71ff1977d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-arrow-circle-right</value>
      <webElementGuid>e7fde34f-d18a-46ae-a738-73faf993283c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actionItems_renderTableHeaderArray_1706341311974_0_0&quot;)/i[@class=&quot;fa fa-arrow-circle-right&quot;]</value>
      <webElementGuid>c4912aaf-d875-4991-824c-fafa99fc909e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboard/Leave/iframe_Self services_homePageFrame</value>
      <webElementGuid>3c8c9058-6540-45c7-940a-8211f6ff09b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='actionItems_renderTableHeaderArray_1706341311974_0_0']/i</value>
      <webElementGuid>f69ff3e8-f92b-43e1-bed2-e35c3a58da79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a/i</value>
      <webElementGuid>7d3d9a72-faa0-46ed-a08a-4fa667734ec1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
