<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_endDate</name>
   <tag></tag>
   <elementGuidId>dcbe04e1-8fa5-476f-939e-1b8b2965ae47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @name = 'date_dataObject.endDate' and @id = 'endDate' and @placeholder = 'End date' and @ref_element = 'Object Repository/Leave/iframe_Self services_homePageFrame']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='endDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#endDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e4ab33b2-ab03-4570-aeec-f023a8393a3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control cal hasDatepicker</value>
      <webElementGuid>3b43cc40-da4f-43f0-b3ac-8a5e7f8229e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c5e0b7a1-0ba1-421f-adf1-7f807f35072f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>date_dataObject.endDate</value>
      <webElementGuid>b3ec4dda-3397-43e3-ba02-c64471508ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>endDate</value>
      <webElementGuid>035dd333-036a-4c72-bfd3-fc16755b530d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6e0ea108-9e5b-4263-9dcb-42152188a5f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:calculateDays('Yes', '');return false;</value>
      <webElementGuid>73385213-e116-4318-896f-60b434cdd307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>End date</value>
      <webElementGuid>f5a1ca0d-feec-4c6f-983e-83c3c4d0f37b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;endDate&quot;)</value>
      <webElementGuid>910b0836-31e6-4a95-9e00-788ed6117c77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboard/Leave/iframe_Self services_homePageFrame</value>
      <webElementGuid>01624436-840d-4e0e-b67b-2366a6791d1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='endDate']</value>
      <webElementGuid>2cd8e297-9c40-4c23-93ed-fc80a4680f20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='durationCtr']/div[2]/input</value>
      <webElementGuid>f0f9c76b-335a-40c2-a2d6-6dae64616f7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div[2]/input</value>
      <webElementGuid>80c35d9d-b4a9-4533-8078-4e0d78747748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'date_dataObject.endDate' and @id = 'endDate' and @placeholder = 'End date']</value>
      <webElementGuid>99f22ccc-cb00-445c-bc54-86ebdba27778</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
