<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Starts from second-half of 2301_dataObject.firstHalf</name>
   <tag></tag>
   <elementGuidId>bc7d2b7b-59af-4cb2-b351-d382971eeac0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='firstHalf']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#firstHalf</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>11bca02e-c126-4775-9de0-977c8283a0a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dataObject.firstHalf</value>
      <webElementGuid>287b8391-4b86-4fb3-a047-a02c933a8e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c1bc0818-ea26-49ca-b14d-9249cb74c107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>firstHalf</value>
      <webElementGuid>76113106-bdbd-4f53-98b3-db4686727043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e7d15b88-add4-4344-abd2-51a8b6f4424d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:calculateDaysOnCheckBox('');return true;</value>
      <webElementGuid>87528c9d-13c4-4ab4-afef-be225daf3fc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;firstHalf&quot;)</value>
      <webElementGuid>5da146a7-db09-46b0-8637-13c53d9b2fc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Dashboard/Leave/iframe_Self services_homePageFrame</value>
      <webElementGuid>f1cf03d5-2ac7-47d4-8371-f388c6bfb824</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='firstHalf']</value>
      <webElementGuid>65785b75-a94f-4710-b304-8b1946b25083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leaveDetailSection']/div/label/input</value>
      <webElementGuid>bac1b18e-c937-48e4-9d21-3c9e5043186b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/label/input</value>
      <webElementGuid>2abfbdd3-36e7-44eb-9023-965e2bc3a1e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'dataObject.firstHalf' and @id = 'firstHalf' and @type = 'checkbox']</value>
      <webElementGuid>97531278-601e-4fcc-9000-33f76031f3d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
