<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Error_Message_Login</name>
   <tag></tag>
   <elementGuidId>9fdfa155-1c77-4d5f-9730-52a8c1e897bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#m771</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/form[3]/div/div/div/div[1]/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>621e30e5-c1da-425d-abcd-ff667e464b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>err</value>
      <webElementGuid>bd03f11f-1ca4-4ee3-a8f1-f220fe158dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>m771</value>
      <webElementGuid>ef83dd0a-4009-43c2-a5c8-2cc770805502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The login credentials are not correct. Please contact your HR Manager or Administrator for support.</value>
      <webElementGuid>34b38c8f-5ea5-4608-b9cb-2978b5d981fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;m771&quot;)</value>
      <webElementGuid>ee488bc2-d47a-45ca-8f7b-ab0ba9a7cc6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='m771']</value>
      <webElementGuid>05c16075-9385-4c91-bb59-4fdaf9745fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Should be checked if you are on a public computer.)'])[1]/preceding::div[2]</value>
      <webElementGuid>fd1d4ff1-415d-4b05-9994-8a026e734d67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='The login credentials are not correct. Please contact your HR Manager or Administrator for support.']/parent::*</value>
      <webElementGuid>99673afb-1ba7-41ec-acc7-b75a0cc11fd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div</value>
      <webElementGuid>3d333ed0-e7ac-4e59-a1eb-dbe26771a3f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'm771' and (text() = 'The login credentials are not correct. Please contact your HR Manager or Administrator for support.' or . = 'The login credentials are not correct. Please contact your HR Manager or Administrator for support.')]</value>
      <webElementGuid>0fb4b459-74d3-459e-b83c-9f47af811eb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
