<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_If checked, login details will not be saved as a cookie_isPublicComputer</name>
   <tag></tag>
   <elementGuidId>6210243a-ee1a-4b83-b7cc-afa73d1a90a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isPublicComputer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='isPublicComputer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>45d8d428-2c67-492d-b6e9-d5411b984672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6ecc95b1-38f2-40ab-a86a-c48d09fbaad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isPublicComputer</value>
      <webElementGuid>21eae036-ea5d-4ce3-b22e-88eb7fc0aa80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setUserDtl();</value>
      <webElementGuid>a320f42c-a9ec-4187-8831-c229555c6586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isPublicComputer&quot;)</value>
      <webElementGuid>a473da64-cd70-4fb4-85de-7c7dfe534713</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='isPublicComputer']</value>
      <webElementGuid>b508808b-b21a-455c-91cf-d6812186ad58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>a4fe3d9c-117d-4c8e-a981-c9c216fb7ec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'isPublicComputer']</value>
      <webElementGuid>d5b25e2f-0dc4-4431-bff9-2504e5c10040</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
