<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Company Id_location</name>
   <tag></tag>
   <elementGuidId>1fb89d21-a12f-4e27-94c4-66157e0a29b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#companyNameId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='companyNameId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>152f6850-1f36-400a-a209-ab7f1c522367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9979f45c-1bd1-410c-b656-b58b1837b308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Company Id</value>
      <webElementGuid>2ba1a33c-b4af-43e5-9cfa-c7ed97f32448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>48d9a008-05f7-48b9-899f-be81ad68d140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>companyNameId</value>
      <webElementGuid>92bd0f3f-a3c5-48f7-9404-5a07e5809325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>location</value>
      <webElementGuid>3aaac81d-f2a2-4d91-b945-62489f7a18fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;companyNameId&quot;)</value>
      <webElementGuid>1d2c0bca-293f-44b9-9e34-94b9e2999d14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='companyNameId']</value>
      <webElementGuid>079c1d35-532c-4b29-b15c-725733df7663</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div[3]/div[2]/div/input</value>
      <webElementGuid>ea6d7ca8-8727-4990-b343-86ea4d1215d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/input</value>
      <webElementGuid>c4b8d47f-e579-41e1-8550-e9fd88e12ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Company Id' and @id = 'companyNameId' and @name = 'location']</value>
      <webElementGuid>15ae4616-d2fb-44b2-b217-9e9c13a4a43d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
