<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Certification</name>
   <tag></tag>
   <elementGuidId>2600897f-d5bb-44b4-8c7b-ea9b1561eeeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.personalprofile > div.col-md-12 > div.sec-button > #btn_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='btn_1'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6a0f0176-db85-420c-811c-4ba44266325e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_1</value>
      <webElementGuid>18e99e4b-d1ca-42c8-9bd3-e19ec8f7bfec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Certification</value>
      <webElementGuid>72f9ea35-751c-4afb-aca7-104f481ef4c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>addRecordDialogEmpQualificationDetail('2');return false;</value>
      <webElementGuid>b3c87966-57da-41c1-bfdc-0d882cff72fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Certification </value>
      <webElementGuid>34dd286b-8c01-4a33-8bf8-cf1d62d8f993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qualificationDataDiv&quot;)/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;personalprofile&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;sec-button&quot;]/a[@id=&quot;btn_1&quot;]</value>
      <webElementGuid>71f5854d-7843-4185-a7e2-8119f7112b28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/self_Service/Profile/iframe_Self services_homePageFrame</value>
      <webElementGuid>9e0614e6-3ac1-4743-8a9d-bee0019dcdc3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id='btn_1'])[2]</value>
      <webElementGuid>d43d1289-0a7b-4e1e-9600-213f1fc55e34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='qualificationDataDiv']/div/div/div[11]/div[2]/a</value>
      <webElementGuid>21900bd4-77ca-445a-8d82-7d96a4b56344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Certification')]</value>
      <webElementGuid>990aaccf-e9c5-4ef9-9adb-7f7a79c7d22d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Education'])[5]/following::a[1]</value>
      <webElementGuid>3f5c0b15-2804-4e03-b5ad-d384ef5cc6fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C-DAC'])[2]/following::a[3]</value>
      <webElementGuid>0cca185d-4ab7-4d0d-bd51-7150cefa42ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Experience'])[3]/preceding::a[1]</value>
      <webElementGuid>91faf6de-bd1a-4b93-a9b7-c9083308824a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View or edit your current or past job experience.'])[1]/preceding::a[1]</value>
      <webElementGuid>a37f8c41-ad49-4667-95b1-7716800cba95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div[2]/a</value>
      <webElementGuid>db444056-e69e-49d8-ae71-72583c5e023d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btn_1' and @title = 'Certification' and (text() = ' Certification ' or . = ' Certification ')]</value>
      <webElementGuid>76bd96a9-da90-49cd-b532-cccd66ddb00a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
