<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dependents</name>
   <tag></tag>
   <elementGuidId>4de78f0a-f6a0-4056-9c5e-7b744238e907</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='btn_0'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.sec-button > #btn_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bc80c756-c7cf-4ae3-8ba9-c97266ed7020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_0</value>
      <webElementGuid>b8cdfe49-5b5c-4a7b-a915-3ff781a0829b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:triggerPersonalDataModes('AddButtonDependentInfoMethod');return false;</value>
      <webElementGuid>08df3568-6e2b-4232-adae-b4b6ae4c80a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dependents </value>
      <webElementGuid>da3b2f2d-8d96-4f33-b9c0-bee37c5aed4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personalDetailsDiv&quot;)/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;personalprofile&quot;]/div[@class=&quot;detail_profile&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;sec-button&quot;]/a[@id=&quot;btn_0&quot;]</value>
      <webElementGuid>3fd3fc89-4d9e-4bb0-846a-5802e708fd11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/self_Service/Profile/iframe_Self services_homePageFrame</value>
      <webElementGuid>939cbac6-9954-487c-acbd-68220c0fc5b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id='btn_0'])[2]</value>
      <webElementGuid>a02d6b0a-3d8d-4543-b3a5-142703613c6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='personalDetailsDiv']/div/div/div/div[3]/div/a</value>
      <webElementGuid>419b6c54-213f-4787-ab7b-694e7546711b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Dependents')]</value>
      <webElementGuid>4e7e9a52-d909-4dfe-b574-921e51f3a9fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Arabic{Basic Knowledge}'])[1]/following::a[2]</value>
      <webElementGuid>1315a4ad-f961-4b16-b8cf-e6d6dbb85813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Languages known'])[1]/following::a[2]</value>
      <webElementGuid>f03cb297-3929-4d83-9028-68e971e9dfa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beneficiaries'])[2]/preceding::a[1]</value>
      <webElementGuid>59880a9e-6517-41b1-841c-67943644ac3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other details'])[1]/preceding::a[2]</value>
      <webElementGuid>7113d58c-bba6-463d-9b39-0f6d70b5469d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a</value>
      <webElementGuid>3a5a793b-59f3-4e03-98a8-be4ce25e4a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btn_0' and (text() = 'Dependents ' or . = 'Dependents ')]</value>
      <webElementGuid>f8dc3534-563c-4976-a268-36c1208c993e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
