<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Education</name>
   <tag></tag>
   <elementGuidId>b0131edf-d56d-4cd7-a67a-8f8b37c5c16c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.personalprofile > div.col-md-12 > div.sec-button > #btn_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='btn_0'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>12011e8f-6c69-4070-94d5-3c48be41ae8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_0</value>
      <webElementGuid>b8a0092b-fc79-4f59-a5cc-bd09676ce733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Education</value>
      <webElementGuid>adbce0fc-5463-48eb-b616-5c3f7051cedf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>addRecordDialogEmpQualificationDetail('1');return false;</value>
      <webElementGuid>3269ea49-3778-4ae4-bcc3-8cea1b30df3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Education </value>
      <webElementGuid>f0b2d0c8-39dd-4851-8d21-a65e678343cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qualificationDataDiv&quot;)/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;personalprofile&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;sec-button&quot;]/a[@id=&quot;btn_0&quot;]</value>
      <webElementGuid>55cd400b-0238-4907-89d3-5d9a42a9ab22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/self_Service/Profile/iframe_Self services_homePageFrame</value>
      <webElementGuid>68c84c6a-b521-488e-9d03-8bc6a968a598</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id='btn_0'])[4]</value>
      <webElementGuid>cac4f686-60b8-4478-944f-bc0bd3dfa6f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='qualificationDataDiv']/div/div/div[3]/div/a</value>
      <webElementGuid>bfb9441f-01b7-4cc3-adab-f35b7618213d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Education')])[3]</value>
      <webElementGuid>17fe1218-3742-483e-8d62-34dbf4d6f167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No records are available'])[1]/following::a[1]</value>
      <webElementGuid>4c946080-2c7d-40c9-861f-56cbf1f91b83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Education and certifications'])[3]/following::a[1]</value>
      <webElementGuid>175defff-ccaa-40ce-ab8a-d516da924932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Certification'])[1]/preceding::a[1]</value>
      <webElementGuid>60e75d6c-7460-4baf-a6c7-711de138983d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Experience'])[3]/preceding::a[2]</value>
      <webElementGuid>580c4349-a723-49c8-aa01-97ada7d2430b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Education']/parent::*</value>
      <webElementGuid>a496fb7e-59c8-4efc-918e-df052ac5bd0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/div/a</value>
      <webElementGuid>e0c05eee-1edb-4075-a002-4d4d0517a85c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btn_0' and @title = 'Education' and (text() = ' Education ' or . = ' Education ')]</value>
      <webElementGuid>90eec5f6-5c57-4af4-85a6-31958ae5fd25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
