<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View or Edit Profile</name>
   <tag></tag>
   <elementGuidId>7394ea66-43ce-42a9-8d80-9ad1a9e550b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#secondary_link_myProfileOverview</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='secondary_link_myProfileOverview']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cbd49a2b-329d-4280-969b-cda2852e1611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>15ed8443-4946-490f-886e-2fca756f1100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>secondary_link_myProfileOverview</value>
      <webElementGuid>abfd20fc-2c73-433f-a372-dc80470ad3e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>encryptURLForPanel('mod=MyProfileOverview');return false;</value>
      <webElementGuid>cdd503fc-18f2-44c5-9037-45445bf323a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-view</value>
      <webElementGuid>6e1aca2f-bd22-47d9-a53a-04764022670a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View or Edit Profile</value>
      <webElementGuid>0cbdaf75-4250-4c98-ae0f-e95b9633daf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;secondary_link_myProfileOverview&quot;)</value>
      <webElementGuid>d57dbc73-f133-4d66-b80a-7238a6254a9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/self_Service/Profile/iframe_Self services_homePageFrame</value>
      <webElementGuid>b237b018-cea8-49a4-b609-1f9fff0988c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='secondary_link_myProfileOverview']</value>
      <webElementGuid>f99bc3de-71cf-4fba-bbc2-4aaee1360650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='displayEmpPersonalDetail_getSecondaryLinks']/div[2]/a</value>
      <webElementGuid>22a0f7d7-49fc-4c1e-9d02-3fee6247dea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View or Edit Profile')]</value>
      <webElementGuid>221dd1ec-1370-43ae-a696-2e36c68b1af2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[6]/following::a[1]</value>
      <webElementGuid>54dd33e9-0cad-4f10-b45a-7ea1c331c9b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave'])[1]/preceding::a[1]</value>
      <webElementGuid>9d85344c-4e2b-4076-b934-94975988f30b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View or Edit Profile']/parent::*</value>
      <webElementGuid>fdae4c9a-4a4f-42b1-93ff-8b2b0f17d4ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0);')]</value>
      <webElementGuid>bb3a3adb-982f-4962-a7a4-37a84accfe05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>2676032e-e5ca-40b1-9b0a-99ea0b66c855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'secondary_link_myProfileOverview' and (text() = 'View or Edit Profile' or . = 'View or Edit Profile')]</value>
      <webElementGuid>08c62de6-a539-4bce-b22b-4e946667c791</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
