<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ok</name>
   <tag></tag>
   <elementGuidId>7ddeaed6-ea89-47e3-a804-6bc3cd0e8c4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#21c074ff-ceb7-4e74-89c6-38f59a681a93</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmation!'])[1]/following::button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b91d1bfd-0163-4aea-ba07-d56f939afcd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>da398d29-6e55-4586-8506-e7de714c66e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>21c074ff-ceb7-4e74-89c6-38f59a681a93</value>
      <webElementGuid>2592bc24-9bbf-4137-b955-c751edd53c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ok</value>
      <webElementGuid>9e3066f3-a782-46e2-aa20-210ad207def7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;21c074ff-ceb7-4e74-89c6-38f59a681a93&quot;)</value>
      <webElementGuid>25317967-6951-473b-b63c-b1111db21549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/self_Service/Profile/iframe_Self services_homePageFrame</value>
      <webElementGuid>56d7bae6-9015-488a-93f2-83b581840f4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='21c074ff-ceb7-4e74-89c6-38f59a681a93']</value>
      <webElementGuid>3cc30c2c-5d75-44e6-ade0-c82ef4cbe839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='89efbf95-a69e-4648-a5ca-f3e4c011685b']/div/div/div[3]/div/div/button</value>
      <webElementGuid>42fcec82-6573-473a-b97b-873fcd673f34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Record has been added successfully.'])[1]/following::button[1]</value>
      <webElementGuid>bc60a306-2328-4f6f-bf0b-d2e9bfab1516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmation!'])[1]/following::button[1]</value>
      <webElementGuid>cd35ea18-901d-4f08-9bbf-6d152e94c13b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ok']/parent::*</value>
      <webElementGuid>9dec015a-d62d-41e6-be77-fac89ca49ed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>b64fe326-aed0-46be-9eb4-ee2eec316be1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '21c074ff-ceb7-4e74-89c6-38f59a681a93' and (text() = 'Ok' or . = 'Ok')]</value>
      <webElementGuid>b47b12e7-f465-4fc8-984e-1dce49230f77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
