<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_verify_message_experience</name>
   <tag></tag>
   <elementGuidId>94a2a387-4666-4625-85bd-5c65916be6f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='snackbar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#snackbar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3426f2de-2717-43ee-a662-3360305bf42e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>snackbar</value>
      <webElementGuid>03a2f3ce-3fd7-4560-864f-318f62366462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>showSnackbar</value>
      <webElementGuid>e37db8d8-d8b5-4bf5-9378-e0ee2aa77674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thank you for submitting personal details changes. The request has been sent to your HR Manager(Testbits Training).</value>
      <webElementGuid>ec1243f6-d89e-45cb-aab5-7b38f7e38269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;snackbar&quot;)</value>
      <webElementGuid>59569b68-6c3d-4985-b1ec-39e0d16a3a3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/self_Service/Profile/iframe_Self services_homePageFrame</value>
      <webElementGuid>4d9b4222-3396-4a28-8d67-acdfb8c99347</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='snackbar']</value>
      <webElementGuid>67a74d29-99a9-429f-a45a-fd5ed6ad9c1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attach document'])[1]/following::div[16]</value>
      <webElementGuid>c0b0eca3-9259-4329-a7a1-d2d883099129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Specific contributions'])[1]/following::div[18]</value>
      <webElementGuid>69d6c002-62d6-4c3a-a7a9-c868d5dd2c17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[4]/preceding::div[2]</value>
      <webElementGuid>23fdd883-71bd-41b9-baed-5387eac0535a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'snackbar', '&quot;', ')')])[1]/preceding::div[10]</value>
      <webElementGuid>12d53c0a-549a-4371-895e-6c54268608ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[3]/div[5]</value>
      <webElementGuid>613bb712-f677-43f2-bbf7-22dc575bc524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'snackbar' and (text() = 'Thank you for submitting personal details changes. The request has been sent to your HR Manager(Testbits Training).' or . = 'Thank you for submitting personal details changes. The request has been sent to your HR Manager(Testbits Training).')]</value>
      <webElementGuid>59bda99e-a8c6-46be-814e-27c5d81c5940</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
