<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Self services</name>
   <tag></tag>
   <elementGuidId>cb968a46-98d5-46ec-8ddb-b4d4bb2862d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#transact</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='transact']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ba60dedd-8c5a-4bd9-935a-886c2ebc8300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>transact</value>
      <webElementGuid>79a81724-8b5a-42d0-8cc3-803389a9af97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v10-side-menu-item </value>
      <webElementGuid>0d14486e-2b1e-4979-b9e8-dd0cd927c878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>displayURL( 'runet.do?activity=submit&amp;mod=transact');return false;</value>
      <webElementGuid>4dd73493-49cb-4952-9dbd-e12c2a50eddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Self services</value>
      <webElementGuid>38ef5284-3103-4949-a0a3-e9338baf5a06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transact&quot;)</value>
      <webElementGuid>d49ddf2b-ee2f-4b49-8b70-9b446421eb3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='transact']</value>
      <webElementGuid>63f35b09-66fd-40ef-9d93-464749d699d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='left_side_menus']/div/div[2]</value>
      <webElementGuid>d0f9be3a-7253-4c02-a8e8-e558c20a7bf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboards'])[1]/following::div[1]</value>
      <webElementGuid>8c41ed5b-d429-4691-af1e-a4f0ab9ca0a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[5]/preceding::div[35]</value>
      <webElementGuid>1e637e3c-ff35-44cb-be1f-78a1d3dfc0bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]</value>
      <webElementGuid>3b1dd899-f2a9-47eb-812e-b60593e10591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'transact' and (text() = 'Self services' or . = 'Self services')]</value>
      <webElementGuid>b8d9ed63-f662-4960-95fa-6727d33eb183</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
