<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_otherDetails_dateOfAnniversy</name>
   <tag></tag>
   <elementGuidId>0aa41d35-84bc-4cf5-87f9-945f9a487dfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#doanni</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='doanni']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>05114715-bfcb-4aba-95ed-c6c6b67ba349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>397ffc84-c7b0-49de-92d3-cbd2a169edb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>doanni</value>
      <webElementGuid>c1a5d47e-0b9e-4f45-a4ae-f7a8eaf26044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>date_empSmallTeo.doanni</value>
      <webElementGuid>8ff6654e-57c7-44ae-8c9e-0de162e68592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control cal hasDatepicker</value>
      <webElementGuid>0c8db620-3031-4fc4-929b-2cfbb7d53b5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;doanni&quot;)</value>
      <webElementGuid>0491c978-9364-4730-897f-0b06e249b07e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/self_Service/iframe_Self services_homePageFrame</value>
      <webElementGuid>e825fd4a-9a05-4e49-a1eb-2ae42a37a066</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='doanni']</value>
      <webElementGuid>f9ae47df-791d-4779-82b5-7d20c2453556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div[6]/div/div[3]/label/input</value>
      <webElementGuid>d19fab7c-3958-49c1-a716-89ffedd42e20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label/input</value>
      <webElementGuid>cbb686e5-1487-4a03-a85c-e3d79f529214</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'doanni' and @name = 'date_empSmallTeo.doanni']</value>
      <webElementGuid>c21918af-582f-4069-aa6f-660e31668483</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
