<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_otherDetails_Domicile</name>
   <tag></tag>
   <elementGuidId>9bb4bfe3-31c6-43a0-9a6f-ca71412ffbf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#domicile</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='domicile']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>571499fe-83bf-47cc-9c5a-9e2bfb9908e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2f27919b-c0af-4f84-a77d-d5c051eead09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>domicile</value>
      <webElementGuid>ca4468f9-0e2c-478a-96d9-e5feb2dc28af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>empSmallTeo.domicile</value>
      <webElementGuid>68b66d84-64d1-4f25-afcf-36adf8994ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b1a0c573-3d9a-4b24-ba46-fc41e6fcb7f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;domicile&quot;)</value>
      <webElementGuid>9076f795-a989-4ecd-abc1-85bac198f8df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/self_Service/iframe_Self services_homePageFrame</value>
      <webElementGuid>dcfbf070-ed94-41b5-82ed-2ea40fcf8ec7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='domicile']</value>
      <webElementGuid>9b2e24df-e729-4472-8be8-aa02f568857d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div[6]/div/div/label/input</value>
      <webElementGuid>70ae22c9-8de7-4557-957c-581f0c6208fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>462fc84e-59b0-4ff1-a722-3a5f56d83ac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'domicile' and @name = 'empSmallTeo.domicile']</value>
      <webElementGuid>e0f31315-7767-44be-a047-46a34c565d5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
