<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mobile_dataObject.mobile</name>
   <tag></tag>
   <elementGuidId>8989c7f3-f123-4b6c-aa25-475b443666cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mobile</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mobile']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f7787638-4158-47f7-a108-649e1a4087f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>01e1b654-d3de-4489-9fcf-297fe58c2a35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dataObject.mobile</value>
      <webElementGuid>b8a7ce88-32fc-4efa-adef-00a8a4f2a0da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>2dfc2ae3-56b0-4533-9681-cdb783922654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>textLimit(this, 20);</value>
      <webElementGuid>0c082d02-5740-4238-b77f-e81ae75c9140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mobile</value>
      <webElementGuid>5e53bbcb-d6d8-47ee-8c5d-c3240c1a4e0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>fb57495f-8362-46be-ac73-5a038e1ad5ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mobile&quot;)</value>
      <webElementGuid>5bb9fd8d-a6e5-49cd-9012-cf5235a8c733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/self_Service/iframe_Self services_homePageFrame</value>
      <webElementGuid>31ce9102-e471-4706-8cbe-e46f2f018adc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mobile']</value>
      <webElementGuid>f9bada2d-fc7f-4f67-a2fe-572da8e00af0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div[6]/div/div[6]/div[2]/div[2]/input</value>
      <webElementGuid>b99795fb-a14b-4ccf-bf2e-eb6d4c4d9fb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>76c7491a-bd7e-447e-8025-4ab2e55aff2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'dataObject.mobile' and @id = 'mobile']</value>
      <webElementGuid>23bce3f2-0649-46de-bd74-dc15de1dd7c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
