<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_highestQualification</name>
   <tag></tag>
   <elementGuidId>580ff5f0-a0cf-46ab-9600-9a11a95ffbdd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isHighestQualification</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='isHighestQualification']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>759b630e-72c4-4d9f-b5ca-31e902a757ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>55e02c5c-b762-41f3-b7ed-e28ddfd20d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isHighestQualification</value>
      <webElementGuid>bd208d29-f262-46d1-b9ae-219319b3f38d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isHighestQualification&quot;)</value>
      <webElementGuid>e9f61cfa-0b8b-4a4a-ac00-59ae7e01541a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/self_Service/iframe_Self services_homePageFrame</value>
      <webElementGuid>c2dc58f0-16fa-4867-b436-98a9270a498f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='isHighestQualification']</value>
      <webElementGuid>b66a8509-1ca7-4603-b8ca-d648a77f06a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div[4]/div/input</value>
      <webElementGuid>3b60dc25-409c-4ec4-8bde-cc57ffba287c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>f8369f95-7a4c-4652-b918-9ca5c1ab23f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'isHighestQualification']</value>
      <webElementGuid>a6a4c3a8-8709-441a-a2ca-5f309a8314c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
