<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_education_duratiion</name>
   <tag></tag>
   <elementGuidId>c632bbd5-5fe5-4f8d-b72c-d4d9d87e0c28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#duration</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='duration']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3e52bfc3-0b9c-4b7d-85c1-7be99253c932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c71aa763-74ce-4848-bae6-85e37b212ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>duration</value>
      <webElementGuid>665e11a3-8791-470e-9992-aa62af8861cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>duration</value>
      <webElementGuid>1aee2f54-4060-482a-add6-ae78f24abe9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3f80faf5-9b13-472c-a279-d78df2cc7a24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;duration&quot;)</value>
      <webElementGuid>a7c7f15b-efaa-431a-b49a-0550e867f0ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/self_Service/iframe_Self services_homePageFrame</value>
      <webElementGuid>25ca3591-8d40-4818-b10b-c1072f5f6443</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='duration']</value>
      <webElementGuid>b05fea0e-b70f-4eb6-902d-660af4c5eb30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div[4]/div[4]/div/input</value>
      <webElementGuid>1ae00ff6-a334-4004-862b-83a08b7f9f59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[4]/div/input</value>
      <webElementGuid>fe9e93ba-ef96-4339-b95b-30b8c4d5e76b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'duration' and @id = 'duration']</value>
      <webElementGuid>2c5b1c0a-54ff-4b7b-8e34-23f3ac98e4c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
