<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zip code_dataObject.pincode</name>
   <tag></tag>
   <elementGuidId>0ecf6a16-b17c-461f-9539-3e7751a78b2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pincode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pincode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bbd2993b-5fe0-4055-9bf7-b20a08376414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4e5563a8-92f9-4547-a42f-32a9c3aebc90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dataObject.pincode</value>
      <webElementGuid>dbe639f6-7ccd-4671-9de9-c47e3085f460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>be0e0313-c759-4b85-b626-a0a03fc12b23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pincode</value>
      <webElementGuid>5d174066-5b95-45e9-ac30-d8f86ab01ff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6ef65023-f131-491a-a8f1-f1b05bb7e950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pincode&quot;)</value>
      <webElementGuid>4d957527-85c0-4ce3-9b94-1c17fedace33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/self_Service/iframe_Self services_homePageFrame</value>
      <webElementGuid>b4964753-8b27-4509-ad22-02064bd19951</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pincode']</value>
      <webElementGuid>a79bbfce-f6af-4f49-9381-78ea115b3519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div[6]/div/div[5]/div[3]/input</value>
      <webElementGuid>c02f2935-6ce7-4b6c-9c9a-7930d7f3b182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/input</value>
      <webElementGuid>8dc389cf-f8dc-420a-9ab1-d6343f85fdfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'dataObject.pincode' and @id = 'pincode']</value>
      <webElementGuid>389be935-a5d8-4767-a026-f4aec64e4bd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
