<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City_dataObject.fk_city</name>
   <tag></tag>
   <elementGuidId>87ecc587-5724-489b-b890-67754b26d179</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fk_city</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fk_city']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db4771e9-be15-45a4-988a-7419eb4e639f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>223e8fdc-641c-4544-baa3-3b2e462b2c81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dataObject.fk_city</value>
      <webElementGuid>7902687c-7b7c-4d63-be6d-a34952cc9fbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>09487eda-11a9-4287-8f73-19b51f059c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fk_city</value>
      <webElementGuid>0348f6e0-4105-4ca1-b4e7-1ed3f2202a86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>49a22a28-968c-4c87-a504-5b5ecde99105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fk_city&quot;)</value>
      <webElementGuid>cfbdf307-f708-4117-8fcc-d28e635ce6f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/self_Service/iframe_Self services_homePageFrame</value>
      <webElementGuid>ee78f7a0-ec76-4409-b9c1-3bd5512fba5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fk_city']</value>
      <webElementGuid>8949373c-422d-4e84-814b-05b850b81e95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div[6]/div/div[5]/div[2]/input</value>
      <webElementGuid>5b738958-68fc-427f-962b-fe34c615e9e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/input</value>
      <webElementGuid>2728236f-82bd-4ce9-b2a4-65ca80eec7b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'dataObject.fk_city' and @id = 'fk_city']</value>
      <webElementGuid>27d7fb0d-8640-41a8-8168-1475f9682a95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
