<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_certification_renewal_date</name>
   <tag></tag>
   <elementGuidId>73b38be8-de20-4e16-93a1-e1def6e2ba21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#stringp10</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='stringp10']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e82a995b-69b2-473e-96b6-b871643b3430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>154bbd52-f9c2-47a4-854f-1239b105ea7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>stringp10</value>
      <webElementGuid>73ee35bb-64db-4076-91a8-807a95787f76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>date_stringp10</value>
      <webElementGuid>466d56f7-d293-4a63-8d39-4d8f8df55de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control cal hasDatepicker</value>
      <webElementGuid>57bc53a2-6c5b-4e49-ae49-62a688d0a354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>textLimit(this, 50)</value>
      <webElementGuid>875aefd5-2e71-4429-b10c-dcdfd9b871fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stringp10&quot;)</value>
      <webElementGuid>058ae52c-aa2d-4050-869e-094157f7dfc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/self_Service/iframe__mycontent-right-frame</value>
      <webElementGuid>e77e6b1d-779e-4e3e-8ceb-5af70747422c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='stringp10']</value>
      <webElementGuid>b629ce9e-1972-42e4-81c8-f998464be8e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div[4]/div/div[2]/input</value>
      <webElementGuid>f3da525f-8707-4636-88e4-b926197c9c83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/input</value>
      <webElementGuid>fb93e7a4-53e0-40de-800b-10aea3a138d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'stringp10' and @name = 'date_stringp10']</value>
      <webElementGuid>f4adeb04-8732-4c81-b88b-7f49347ef971</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
