<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_state</name>
   <tag></tag>
   <elementGuidId>2ba676d0-5305-4d3b-9eb8-b56ae170f55b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#countryStateMappingId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='countryStateMappingId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d47ff09b-8950-495b-b421-eb3d208db6cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dataObject.countryStateMppingId</value>
      <webElementGuid>c8206ca8-0910-4114-8f50-a64e42272dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>countryStateMappingId</value>
      <webElementGuid>38f62d9e-0ee4-4311-b593-534edf652f07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f7a0305c-1859-475a-b77b-384f3900329e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JohorKedahKelantanKuala LumpurLabuanMelakaNegeri SembilanPahangPerakPerlisPulau PinangPutrajayaSabahSarawakSelangorTerengganu</value>
      <webElementGuid>9e0d02da-032b-4f88-9778-d4dff67a99cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;countryStateMappingId&quot;)</value>
      <webElementGuid>9883e444-a58c-4303-b636-46dbb45dd7e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/self_Service/iframe_Self services_homePageFrame</value>
      <webElementGuid>59dd06f1-efca-420f-9c62-e7296a125f50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='countryStateMappingId']</value>
      <webElementGuid>5fc4a20f-bfc5-4151-bf67-109aca0a61bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div[6]/div/div[5]/div/select</value>
      <webElementGuid>a60eba66-281a-44cf-b596-1da9f6bbc68b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State'])[1]/following::select[1]</value>
      <webElementGuid>fd0fb258-bfe5-4d80-a97f-d5eb0e5cb0ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/following::select[2]</value>
      <webElementGuid>05593e48-6ce0-4509-81cc-d797050879d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City'])[1]/preceding::select[1]</value>
      <webElementGuid>1b166aad-6e2c-4c45-a7b4-49f38accae4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zip code'])[1]/preceding::select[1]</value>
      <webElementGuid>c56ed6b0-2bef-4b82-9e2e-86b1c97d669e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/select</value>
      <webElementGuid>542a8255-8e78-41bf-906b-f2e5305002ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'dataObject.countryStateMppingId' and @id = 'countryStateMappingId' and (text() = 'JohorKedahKelantanKuala LumpurLabuanMelakaNegeri SembilanPahangPerakPerlisPulau PinangPutrajayaSabahSarawakSelangorTerengganu' or . = 'JohorKedahKelantanKuala LumpurLabuanMelakaNegeri SembilanPahangPerakPerlisPulau PinangPutrajayaSabahSarawakSelangorTerengganu')]</value>
      <webElementGuid>864795c4-5a7b-40e5-a7db-a046fe3d8bbc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
