<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_proficiency</name>
   <tag></tag>
   <elementGuidId>2d637c7d-dfbe-4d95-81aa-63e6f0a8f4c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#languageProficiency</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='languageProficiency']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3bbb8575-ab26-4ef3-a857-ba66c0e2cf92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dataObject.languageProficiency</value>
      <webElementGuid>d514823a-358d-4796-bae7-e68a76af72d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>languageProficiency</value>
      <webElementGuid>5a576c00-6069-40f1-8ae6-0399ce97d37e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>82ee8493-41f4-4df2-ba2c-89d47f797dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Basic KnowledgeOralWritten and OralExpert</value>
      <webElementGuid>e873e931-8c47-48ca-b346-114914c7ee96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;languageProficiency&quot;)</value>
      <webElementGuid>67e88afe-a25e-4b34-a218-21806d28e3e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/self_Service/iframe_Self services_homePageFrame</value>
      <webElementGuid>c2bba853-76ab-46eb-a4d4-49847160a004</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='languageProficiency']</value>
      <webElementGuid>5d21de9f-013c-4445-9855-55a311983062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div[2]/div/div[2]/select</value>
      <webElementGuid>0866ce81-5093-4f87-abd1-8eb29c892797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proficiency'])[1]/following::select[1]</value>
      <webElementGuid>0388fb7c-9c24-4caf-b399-8af9841bf99e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language details'])[1]/following::select[2]</value>
      <webElementGuid>10faf2ae-3ca5-4e88-8e4c-0211871c04da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More details'])[1]/preceding::select[1]</value>
      <webElementGuid>6477ee00-0521-4f60-bb46-107b260983be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::select[1]</value>
      <webElementGuid>0c001f30-c466-4257-b9b9-0663508aa19c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>56c56be1-1647-41a9-80e1-8043233df640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'dataObject.languageProficiency' and @id = 'languageProficiency' and (text() = 'Basic KnowledgeOralWritten and OralExpert' or . = 'Basic KnowledgeOralWritten and OralExpert')]</value>
      <webElementGuid>608daf5c-30a6-4110-b300-5344492ef5a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
