<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_educationType</name>
   <tag></tag>
   <elementGuidId>8453b5af-0935-491c-b001-13e67870549a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fk_qualificationtype</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='fk_qualificationtype']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e57616e6-4dcb-4dbc-b4b7-06d14a924cc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fk_qualificationtype</value>
      <webElementGuid>20652956-2c71-4ee8-af43-6e017cee2635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fk_qualificationtype</value>
      <webElementGuid>eb606a2e-8e18-4160-bb50-8e7ac9c8b0e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2234cb66-63b8-43cb-b8e4-b2c091e31740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>updateSelectOnDataChangeEmpQualificationDetail(this.options[this.selectedIndex].value, 'getQualificationCodes', 'fk_qualification', 'attributeId', 'attributeName');</value>
      <webElementGuid>7e649d60-0a7c-4b59-a9a0-969d602e645e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>---Select---DiplomaDoctorateGrad - EngineerGrad - Non EngineerNon-degree QualPost Grad - BusinessPost GraduateSchooling</value>
      <webElementGuid>c045b20d-c146-4f16-b4e2-7d9cb31ba242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fk_qualificationtype&quot;)</value>
      <webElementGuid>42e75154-9369-4adf-9935-2ff1fd0c6366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/self_Service/iframe_Self services_homePageFrame</value>
      <webElementGuid>866fbacd-5331-4a09-8d9f-3adbd0e6801b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='fk_qualificationtype']</value>
      <webElementGuid>66642511-9406-4d2f-b386-bf47b090094b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div[4]/div[2]/div/select</value>
      <webElementGuid>85fe7f04-4981-4b79-b144-c5cc0b125ba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*Type'])[1]/following::select[1]</value>
      <webElementGuid>62cbb873-1202-4417-adf5-b74c6f7a71e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*Degree'])[1]/preceding::select[1]</value>
      <webElementGuid>a8c5c41b-6230-4c6a-a64a-f78b675cbb4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*College'])[1]/preceding::select[2]</value>
      <webElementGuid>5397853a-59f3-4ea6-b0cf-87d2eb021199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>f7b721d3-8988-4fb6-bb66-dd33c508df57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'fk_qualificationtype' and @id = 'fk_qualificationtype' and (text() = '---Select---DiplomaDoctorateGrad - EngineerGrad - Non EngineerNon-degree QualPost Grad - BusinessPost GraduateSchooling' or . = '---Select---DiplomaDoctorateGrad - EngineerGrad - Non EngineerNon-degree QualPost Grad - BusinessPost GraduateSchooling')]</value>
      <webElementGuid>3f25ad19-d0f5-4592-9c93-25bc6b3d07d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
