<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_certification_types</name>
   <tag></tag>
   <elementGuidId>d03ce513-e000-44cb-b1ca-073a136641f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='fk_certificationtype']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fk_certificationtype</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e0fe0cdd-86a4-4461-94c9-c04ab4ad96a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fk_certificationtype</value>
      <webElementGuid>3d9e1b17-2d70-43c0-b521-11a385fac666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fk_certificationtype</value>
      <webElementGuid>7f7fe805-b4d5-4f55-8860-8984141db2e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>55fc06ab-bf78-483f-ae5d-5ab61285594e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>---Select---C-DACD.C.AMCNASelf Learning</value>
      <webElementGuid>08c474dc-3f6c-4351-9532-163ea97be44e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fk_certificationtype&quot;)</value>
      <webElementGuid>253aa839-cd24-4d6b-ab2e-505adcec37cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/self_Service/iframe_Self services_homePageFrame</value>
      <webElementGuid>10a06522-3003-4e74-844a-acbd253b28f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='fk_certificationtype']</value>
      <webElementGuid>8f3aacc4-039c-468a-bd7a-1b61b77495e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div[4]/div/div/select</value>
      <webElementGuid>76dca458-eaf0-4aa2-8efd-9bf9ea19e097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*Type'])[1]/following::select[1]</value>
      <webElementGuid>e24a7659-2af7-451c-b253-656fc218020f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[1]/following::select[1]</value>
      <webElementGuid>731bae47-9ae4-46f9-9e33-a3d815c326a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You may optionally enter a date here that indicates when the Certification expires.'])[1]/preceding::select[1]</value>
      <webElementGuid>5fd65b1a-1883-4892-9b55-a3f89653e491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>1ef0e90c-2fee-4ce6-8e24-47ad9732b909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'fk_certificationtype' and @id = 'fk_certificationtype' and (text() = '---Select---C-DACD.C.AMCNASelf Learning' or . = '---Select---C-DACD.C.AMCNASelf Learning')]</value>
      <webElementGuid>83bf30ad-0ec7-467d-a7d6-54df7b266adb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
