<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_language</name>
   <tag></tag>
   <elementGuidId>4229591b-c590-4227-b428-04be6d15ef49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#languageName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='languageName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ae081686-7962-4d39-9974-c0f86b601def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dataObject.languageName</value>
      <webElementGuid>35c4d3c2-8ea0-495b-89c6-84c7c5d320a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>languageName</value>
      <webElementGuid>d98dbf5a-5422-4452-90ea-f3dadb4168b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3f8a7f9b-334d-434f-9b20-1b1537fad9b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ArabicEnglishFrenchGermanHindiMandarinSpanish</value>
      <webElementGuid>d937b20e-5202-4c43-8f79-2ce102fbec4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;languageName&quot;)</value>
      <webElementGuid>7601d46c-87ec-4c17-ad9f-1702e743abad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/self_Service/iframe_Self services_homePageFrame</value>
      <webElementGuid>48c1ab3f-5e3b-445f-af6f-c6c2bb5ade63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='languageName']</value>
      <webElementGuid>41aefd31-398a-4745-a967-baccf3a73b14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div[2]/div/div/select</value>
      <webElementGuid>d8026b17-27fa-4179-b28a-83bcecfba498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language details'])[1]/following::select[1]</value>
      <webElementGuid>a66b2213-5624-42bf-9c91-46011a91aa66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Languages known » Add'])[1]/following::select[1]</value>
      <webElementGuid>ed05c688-379f-4560-a6e7-7f24de25574f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proficiency'])[1]/preceding::select[1]</value>
      <webElementGuid>b95e6d37-f554-4feb-9981-7bfcfe9d13ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More details'])[1]/preceding::select[2]</value>
      <webElementGuid>55d745af-1e99-42bc-881f-efdcd6fafeb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>ab4a0b15-8694-49c0-a59a-125fc1ed1966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'dataObject.languageName' and @id = 'languageName' and (text() = 'ArabicEnglishFrenchGermanHindiMandarinSpanish' or . = 'ArabicEnglishFrenchGermanHindiMandarinSpanish')]</value>
      <webElementGuid>274968c4-03a7-4e4a-a901-83131123e371</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
