<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_degree</name>
   <tag></tag>
   <elementGuidId>b48f1a7e-ff57-4e08-bdee-0f7eaced2d88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fk_qualification</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='fk_qualification']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>00a327ec-58ce-4354-b9b0-b62e2008882f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fk_qualification</value>
      <webElementGuid>ac4db8b8-e61a-47eb-aece-b882ba9c74f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fk_qualification</value>
      <webElementGuid>afb61897-e258-4c08-9d0e-c79768088ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>df6f7702-5adc-419a-8320-ecc8ab463da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GraduateBioTechChemical EngineeringCivil EngineeringComp Sc.E&amp;CE&amp;EIndustrial ProductionBSMechanical EngineeringPrinting TechnologyITHigh School</value>
      <webElementGuid>d965671a-2a01-422e-9118-1140fec33cb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fk_qualification&quot;)</value>
      <webElementGuid>5b341b35-5935-4275-acaf-6e370b4877f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/self_Service/iframe_Self services_homePageFrame</value>
      <webElementGuid>c3552020-822b-446f-9b2b-67f03c0b7c6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='fk_qualification']</value>
      <webElementGuid>5fe7449a-907c-454d-9c36-7729b84e3384</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div[4]/div[2]/div[2]/select</value>
      <webElementGuid>fecbd6d5-8ede-4ee7-80b5-7470d804e965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*Degree'])[1]/following::select[1]</value>
      <webElementGuid>0fa7ba25-8393-4786-a0c9-0606c2fd428e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*Type'])[1]/following::select[2]</value>
      <webElementGuid>04fe4960-9c9c-4cd3-a37d-9e55ba5acf5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*College'])[1]/preceding::select[1]</value>
      <webElementGuid>6f46a4f4-0771-4e1e-b3b3-2544e1ed8402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*University'])[1]/preceding::select[1]</value>
      <webElementGuid>441297b6-0475-4150-9b24-4b2ce95a79f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>0e28a663-80d7-4430-b5d7-9e4f18b14a89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'fk_qualification' and @id = 'fk_qualification' and (text() = 'GraduateBioTechChemical EngineeringCivil EngineeringComp Sc.E&amp;CE&amp;EIndustrial ProductionBSMechanical EngineeringPrinting TechnologyITHigh School' or . = 'GraduateBioTechChemical EngineeringCivil EngineeringComp Sc.E&amp;CE&amp;EIndustrial ProductionBSMechanical EngineeringPrinting TechnologyITHigh School')]</value>
      <webElementGuid>998d8738-ee59-4292-a4aa-56c94052fe0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
