<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ok</name>
   <tag></tag>
   <elementGuidId>4d9b9ffe-ffbe-4c4e-9124-43934500d299</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#d782d568-bd41-4f31-95b3-1516df9d432a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7f5a737c-bbe5-42fd-8525-4f6865105fb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>f59049a5-5957-4ea5-8811-42d28c24ce7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>d782d568-bd41-4f31-95b3-1516df9d432a</value>
      <webElementGuid>8e53aeb7-7017-4e49-b3dd-2dd35e0a664c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ok</value>
      <webElementGuid>779aa40e-09a5-4206-95f1-c1dfe175b3aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;d782d568-bd41-4f31-95b3-1516df9d432a&quot;)</value>
      <webElementGuid>9cee9d55-eba6-496f-9f7d-e8400d8c9138</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='d782d568-bd41-4f31-95b3-1516df9d432a']</value>
      <webElementGuid>d2cb922f-aa6e-45d1-8bc7-8a0bfde4e881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='79793ca6-76e0-4c77-8aa1-474752567ab3']/div/div/div[3]/div/div/button</value>
      <webElementGuid>58e4c74a-8c58-4c1a-be33-e49ce222e0d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thanks for submitting your choice.'])[1]/following::button[1]</value>
      <webElementGuid>f25f0f17-25a2-4bd9-8bbe-4c3a66a983f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmation!'])[1]/following::button[1]</value>
      <webElementGuid>58191afd-3577-4453-a916-cc2d4aecece2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ok']/parent::*</value>
      <webElementGuid>de7c717f-e79f-4c5b-b258-a7e5ced78601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>d6475538-b1cc-4079-b2e9-31f79a615ca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'd782d568-bd41-4f31-95b3-1516df9d432a' and (text() = 'Ok' or . = 'Ok')]</value>
      <webElementGuid>24464112-a979-4caf-8cf8-2fb0f0651623</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
