<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_verify_error_feedback_Please select a valid Employee</name>
   <tag></tag>
   <elementGuidId>1e990486-59de-441b-a93e-78c627b544ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#c0e5b51a-b0c4-400b-b01d-d933ea7682b7 > div.modal-dialog > div.modal-content > div.modal-body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/following::div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>88e6ce39-49c0-4f96-b3e1-7f1744e6a536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body</value>
      <webElementGuid>9b9d77e8-11d7-4516-8917-602f62b92994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please select a valid Employee.</value>
      <webElementGuid>1c2e91db-0847-4c46-9c43-2bd4c6f653ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c0e5b51a-b0c4-400b-b01d-d933ea7682b7&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]</value>
      <webElementGuid>6dda1f3c-bb5e-4257-841c-3eafb3685a05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c0e5b51a-b0c4-400b-b01d-d933ea7682b7']/div/div/div[2]</value>
      <webElementGuid>49d24278-e3b4-40c2-b14e-ec5b83b8093f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/following::div[1]</value>
      <webElementGuid>c2d6fe45-078c-441c-91ac-983eb6f88db5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[6]/following::div[2]</value>
      <webElementGuid>76d98ba3-b02a-4499-b46c-97836b258a67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::div[3]</value>
      <webElementGuid>5cf7fcf4-9ff6-4078-8b12-5a89a8249679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div[2]</value>
      <webElementGuid>2681ef9d-7b2c-4044-a47e-587d673747a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Please select a valid Employee.' or . = 'Please select a valid Employee.')]</value>
      <webElementGuid>016b596e-4814-4a7a-852a-7b024e941282</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
