<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_emp  10</name>
   <tag></tag>
   <elementGuidId>1383eb07-c9c5-4cda-b430-e8aac745280e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='1004825']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#1004825</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>97ef1c44-e9c2-4ac5-926a-3e0edc0ff85d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1004825</value>
      <webElementGuid>a00b749f-f577-41ef-8c49-094a9d6ce4b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>optionDivSelected</value>
      <webElementGuid>175879a3-3ee8-4fe1-96a4-b7cefe0ffb9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>emp  10 </value>
      <webElementGuid>c5587784-26e4-401b-9669-f05bb5f89e5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1004825&quot;)</value>
      <webElementGuid>c02f6233-9bc9-4500-9339-68ca85267b43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='1004825']</value>
      <webElementGuid>96142516-a6da-40b4-9eea-ce4fdc210214</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ajax_listOfOptions']/div[10]</value>
      <webElementGuid>22a1673f-9267-4a96-93b5-1d54896e8224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]</value>
      <webElementGuid>ec367fb7-1674-4a54-ac1e-41693b69138b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '1004825' and (text() = 'emp  10 ' or . = 'emp  10 ')]</value>
      <webElementGuid>eb28ccbc-2463-4627-8e2b-437db208401c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
