<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Good morningemp,</name>
   <tag></tag>
   <elementGuidId>3a12b2ab-f6ae-49f3-b4fa-69b41490e3d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='displayPageContent']/div/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.font_display_medium_bold.welcome-h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8eed38fa-d60a-498f-97f7-70b49ec6463e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font_display_medium_bold welcome-h1</value>
      <webElementGuid>a12514d6-473f-4433-b4d0-185108c7edf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Good morning emp, </value>
      <webElementGuid>dccfd52f-a156-43a1-b559-293b416162f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;displayPageContent&quot;)/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;v10-content-section&quot;]/div[@class=&quot;col-md-9 col-sm-12&quot;]/div[@class=&quot;font_display_medium_bold welcome-h1&quot;]</value>
      <webElementGuid>67357c0e-21f3-4e19-9930-bce3422b5d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu Toolbar/iframe_Self services_homePageFrame</value>
      <webElementGuid>92699627-8a97-4416-8c38-f3001e3a6e4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='displayPageContent']/div/div[2]/div/div</value>
      <webElementGuid>ebc701d6-7ce3-4dc6-87c7-1fa559c2e48e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wed 31 Jan, 11:36 AM'])[1]/preceding::div[2]</value>
      <webElementGuid>0629b27a-60dc-4fd2-86f8-b011a3af4ce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div</value>
      <webElementGuid>c087569b-cf1c-4aa0-acc4-0fd239c1c003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Good morning emp, ' or . = 'Good morning emp, ')]</value>
      <webElementGuid>6b4633df-d1af-499d-bb42-5cce43d19d71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
