<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_verify_Notifications (.as Employee)</name>
   <tag></tag>
   <elementGuidId>5a1f1fc2-0f0b-4d58-ab41-dc9856f2f4f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='notificationItems']/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>6f7021fa-ff7c-4b5d-bd76-1ba11b9d0563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Notifications (...as Employee)</value>
      <webElementGuid>21439912-f835-4730-89ea-4349a05ba176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;notificationItems&quot;)/h3[1]</value>
      <webElementGuid>09751e43-e3fe-4815-91c1-ee854211ee98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='notificationItems']/h3</value>
      <webElementGuid>227a08c8-2e55-4e73-ba24-2953d25bed9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[2]/following::h3[1]</value>
      <webElementGuid>37b58186-65d1-4e91-8dc1-699cac83c798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No new notifications. You are on top of everything!'])[1]/preceding::h3[1]</value>
      <webElementGuid>630fb88f-4f68-431a-8401-841dee586be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>c2643dee-3752-45e8-aa5f-b70651f1c19c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Notifications (...as Employee)' or . = 'Notifications (...as Employee)')]</value>
      <webElementGuid>ae8a48aa-dedf-4e73-9e63-8fdbb6003045</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
