<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Rating_pulseRating_2</name>
   <tag></tag>
   <elementGuidId>55686fcb-2b63-4f5f-aab3-4b69f1068f1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='pulseRating_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pulseRating_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ffb090a8-8dc3-4347-afaa-3127732dc5ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/client/tenant-lite/highlightedStarRating.png</value>
      <webElementGuid>0b90dd46-3c56-4aa5-acf1-4a03b9d5b6b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>3.0</value>
      <webElementGuid>7dfa915b-9473-4e9a-a178-846e7a2dc452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pulseRating_2</value>
      <webElementGuid>9ea85be7-7501-48eb-8e0f-eb9a1c9699df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>changeStarRatingOptions('pulseRating','2','5','3.0');setChanged();</value>
      <webElementGuid>e70f1596-0731-43c1-b200-1d1381f710e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pulseRating_2&quot;)</value>
      <webElementGuid>df373c27-4739-4a56-8231-59667668c448</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='pulseRating_2']</value>
      <webElementGuid>103b6c1c-a198-476d-8597-067653683f81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div[2]/div/div[3]/div/img[3]</value>
      <webElementGuid>3781f18f-7582-4609-bb8e-1c6ff65bbda0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='3.0']</value>
      <webElementGuid>b35a1e27-8338-4ffa-8a79-01bf25647d30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img[3]</value>
      <webElementGuid>df72c9f9-6680-428a-a913-fb66177394b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/client/tenant-lite/highlightedStarRating.png' and @title = '3.0' and @id = 'pulseRating_2']</value>
      <webElementGuid>6849cbe6-53a4-42f8-aa2f-8972fae9317b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
