<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Rating_pulseRating_0</name>
   <tag></tag>
   <elementGuidId>e85a08a6-f19c-4037-af0f-436b106b9765</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='pulseRating_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pulseRating_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ce4e0abb-ba63-48ee-aae1-27840ae19ee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/client/tenant-lite/highlightedStarRating.png</value>
      <webElementGuid>f6e0395a-e798-4a8a-a671-cd3084fbce9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>1.0</value>
      <webElementGuid>0cf2914a-174a-4edd-be03-8dab46c70566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pulseRating_0</value>
      <webElementGuid>20115044-af24-4f41-8904-232eefba90b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>changeStarRatingOptions('pulseRating','0','5','1.0');setChanged();</value>
      <webElementGuid>6c4247c8-f762-41a8-9fa3-ed8171f32026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pulseRating_0&quot;)</value>
      <webElementGuid>1c85c5b9-943b-4cdd-93a3-bd13abcc96a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='pulseRating_0']</value>
      <webElementGuid>3223c87a-c79e-421b-928f-c24f681c15d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div[2]/div/div[3]/div/img</value>
      <webElementGuid>e40bfd03-71fa-48ff-9b23-cc96fe07a5fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='1.0']</value>
      <webElementGuid>b7b17313-b3e6-47cf-be86-b2df2b081564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/img</value>
      <webElementGuid>7ace5b69-498f-4211-bd4c-5d71bb060322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/client/tenant-lite/highlightedStarRating.png' and @title = '1.0' and @id = 'pulseRating_0']</value>
      <webElementGuid>f5ef6bcc-a911-4e22-9f5e-ffe4272731a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
