<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Communication_Suggestion_SpecifyArea</name>
   <tag></tag>
   <elementGuidId>a96b41bf-2c49-4640-b2d5-5cbf92d2c87a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='empxtrack_feedback_subject_by_client']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#empxtrack_feedback_subject_by_client</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>35d6e43b-fb8c-4947-956c-3fe68ab6014c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bc3d4238-3237-4a0f-a7cc-9a0dae7b7145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>empxtrack_feedback_subject_by_client</value>
      <webElementGuid>c2a2ae71-fb4f-4f93-a47d-44a648a680a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e1c5cda5-a3a6-4f7f-875d-a4cf83337201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Specify area</value>
      <webElementGuid>d26ebf40-7d5f-42b0-8486-eb2f8e4d120a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;empxtrack_feedback_subject_by_client&quot;)</value>
      <webElementGuid>fe732b06-11fb-42c3-9b6a-16abae3d72b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='empxtrack_feedback_subject_by_client']</value>
      <webElementGuid>483e34a7-10a2-4de3-aa3a-e00a047bdcc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>8a39ec6f-f574-47bb-8c70-e719d2e7806a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>b02d0e51-ab35-437c-aaa1-5543c095f895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'empxtrack_feedback_subject_by_client' and @type = 'text' and @placeholder = 'Specify area']</value>
      <webElementGuid>2ebbe65c-f0bd-4f10-b8ad-1a5b552e71b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
