<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Communication_Suggestion_Check for anonymous submit_checkAnonymousSubmit</name>
   <tag></tag>
   <elementGuidId>c38069be-a1bf-43ca-ac24-7870a1e05cc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkAnonymousSubmit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkAnonymousSubmit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>71407798-f227-478d-99e7-a7c5811b7d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>63b212b3-4d9c-437a-891b-d0d2ee97ef78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkAnonymousSubmit</value>
      <webElementGuid>866e8a80-2491-4c03-bb46-1e04939a911e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkAnonymousSubmit</value>
      <webElementGuid>be0b9094-8fe0-4136-8503-79be4089e169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkAnonymousSubmit&quot;)</value>
      <webElementGuid>64ff8666-a2e9-4160-a7d2-c67a41297e3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkAnonymousSubmit']</value>
      <webElementGuid>be0984ce-1e1a-43b1-a684-6ae7ee706105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div/div[3]/label/input</value>
      <webElementGuid>bd39a020-06b1-4f0c-8816-f92f452ce0b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>99190539-7e5d-4535-b730-d3367bdff80e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'checkAnonymousSubmit' and @id = 'checkAnonymousSubmit']</value>
      <webElementGuid>0a749bea-77ea-4c93-905b-708088187ccb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
