<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Communication_Suggestion_yourSuggestion</name>
   <tag></tag>
   <elementGuidId>663cf124-4ed2-4471-968c-57c53f0609d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='empxtrack_feedback_by_client']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#empxtrack_feedback_by_client</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>4c208ec1-7a55-4aa6-a98c-0560a9a59088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5a832adb-cdb5-4ec9-bfc5-56317621a7f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>empxtrack_feedback_by_client</value>
      <webElementGuid>4523edd0-2227-4020-a861-b85f2b1644bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Your suggestion</value>
      <webElementGuid>f1f73e46-27f1-46e2-996d-22e7f89f005c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;empxtrack_feedback_by_client&quot;)</value>
      <webElementGuid>17a3ba81-2625-4b3a-9e4e-f473c63317f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='empxtrack_feedback_by_client']</value>
      <webElementGuid>9d93746f-537d-4c1d-a7b8-0b4ac84ef913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div/div[2]/div/textarea</value>
      <webElementGuid>6acc24ce-57fc-4e3e-9d74-73b30289dc8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>b69d68a9-5d26-47a0-bf38-d170261979e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'empxtrack_feedback_by_client' and @placeholder = 'Your suggestion']</value>
      <webElementGuid>98984a48-705c-4fc8-aca5-152856a5fb81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
