<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ok_Confirmation_addedEventSuccessfully</name>
   <tag></tag>
   <elementGuidId>43c385fc-1b2e-493f-9584-df95693fc074</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#34ef4c54-2767-4cc8-a507-2d135b567df7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='34ef4c54-2767-4cc8-a507-2d135b567df7']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b0ca8921-5a33-4d57-b5bf-df24a6f478d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>1db29654-200e-4fcb-b37f-02705451d6af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>34ef4c54-2767-4cc8-a507-2d135b567df7</value>
      <webElementGuid>3cd7e0b3-31a4-4ccb-9d02-cbb3b3053027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ok</value>
      <webElementGuid>90c82a8f-4e24-4c50-a77e-85eba6875d76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;34ef4c54-2767-4cc8-a507-2d135b567df7&quot;)</value>
      <webElementGuid>5c49b163-0897-49d5-92dd-3eefafb46e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Empxtrack Search/Page_Home page/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>b17dc60b-48b4-4e98-9106-0e65590173ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='34ef4c54-2767-4cc8-a507-2d135b567df7']</value>
      <webElementGuid>905fdeb6-3b62-47dc-99d9-ffded6113ed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='88e62add-813d-4da7-bf44-3238a6dce103']/div/div/div[3]/div/div/button</value>
      <webElementGuid>72378bbb-82e5-49b0-be3e-d99743da8b9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event invitation has been added successfully.'])[1]/following::button[1]</value>
      <webElementGuid>a13d19e6-2e1c-4dcc-aa85-13af19647f2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmation!'])[1]/following::button[1]</value>
      <webElementGuid>95ac73aa-2c58-44a8-944b-c4829b89ec41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ok']/parent::*</value>
      <webElementGuid>58e362d6-82a7-409a-9eca-386ac92c4e95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>9db9bede-14d5-4f81-8000-2fbd98e376ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '34ef4c54-2767-4cc8-a507-2d135b567df7' and (text() = 'Ok' or . = 'Ok')]</value>
      <webElementGuid>d468b4c4-c452-421a-94a8-805950459518</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
