<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_View details for emp  01</name>
   <tag></tag>
   <elementGuidId>72360c17-6928-4e4d-8dd7-a1c4e34a5133</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhFQpUETrO5wn33JnqGX4w4FSucEcm60J4ck3bHF0HJ3D6GlndnfbXZkHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOncd2jt8n0kE$$panel$$_blank']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3575b5d3-7647-41c5-b55d-1f012155c8c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhFQpUETrO5wn33JnqGX4w4FSucEcm60J4ck3bHF0HJ3D6GlndnfbXZkHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOncd2jt8n0kE$$panel$$_blank</value>
      <webElementGuid>04f80d47-0257-4865-8398-760856778305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>optionDivSelected</value>
      <webElementGuid>e8784e5a-3f8d-4dfd-922c-cee53a757b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View details for: emp  01 </value>
      <webElementGuid>c0dd431c-5644-4b7e-b714-dd31023c1ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhFQpUETrO5wn33JnqGX4w4FSucEcm60J4ck3bHF0HJ3D6GlndnfbXZkHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOncd2jt8n0kE$$panel$$_blank&quot;)</value>
      <webElementGuid>d4254866-f851-41c1-bbbb-8fb42c04a98b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhFQpUETrO5wn33JnqGX4w4FSucEcm60J4ck3bHF0HJ3D6GlndnfbXZkHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOncd2jt8n0kE$$panel$$_blank']</value>
      <webElementGuid>33cbecde-cd22-4221-be97-ffce490584ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ajax_listOfOptions']/div[2]</value>
      <webElementGuid>3e680059-09ba-4d62-ac74-cdbc2d849b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::div[4]</value>
      <webElementGuid>d1683885-5fb6-4e25-ada4-2b5e441f76a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]</value>
      <webElementGuid>f9001aed-bb04-429c-a7cc-d2118a031868</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhFQpUETrO5wn33JnqGX4w4FSucEcm60J4ck3bHF0HJ3D6GlndnfbXZkHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOncd2jt8n0kE$$panel$$_blank' and (text() = 'View details for: emp  01 ' or . = 'View details for: emp  01 ')]</value>
      <webElementGuid>b8c039a0-be1b-4062-884c-569ef51e3074</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
