<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK</name>
   <tag></tag>
   <elementGuidId>9782d751-b876-4c6c-bcbd-ab9df2a67da3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#63525b00-841b-47a3-be0c-7c2af9a4cb07</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2ed22a52-ae6b-4b09-b69b-dbc9e3248092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>236e7c18-a520-40ba-b8e6-b6db876c420d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>63525b00-841b-47a3-be0c-7c2af9a4cb07</value>
      <webElementGuid>c027f64b-a96a-4a14-b718-a25b3bf81f01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>5e1be007-dfaf-4f12-b819-d317ce173cfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;63525b00-841b-47a3-be0c-7c2af9a4cb07&quot;)</value>
      <webElementGuid>523928b1-a853-479a-bc45-e77f28355718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/User Profile Icon/iframe__mycontent-right-frame</value>
      <webElementGuid>d56db788-25a1-41f2-9a23-d4ac542574f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='63525b00-841b-47a3-be0c-7c2af9a4cb07']</value>
      <webElementGuid>728fef98-d59e-47b0-b9b0-a9bc41af558f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='d8ab5824-54f7-4a0c-bf02-65a9869c2861']/div/div/div[3]/div/div/button</value>
      <webElementGuid>a8a92412-10e6-4ed9-9a9f-266e026bc4d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please specify the old password.'])[1]/following::button[1]</value>
      <webElementGuid>91bb4aee-6ecf-40ca-82e8-9ea79ce8a87f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/following::button[1]</value>
      <webElementGuid>7165506c-9fe5-434c-86f2-0fcb338824f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OK']/parent::*</value>
      <webElementGuid>71207f36-a662-4169-984d-af18f2955677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>6b59bc1e-0937-4fc3-b432-2cbd6badd5a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '63525b00-841b-47a3-be0c-7c2af9a4cb07' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>881e21e7-7001-49d5-aa2a-221acf678f51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
