<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_e_icon_scrollDown</name>
   <tag></tag>
   <elementGuidId>425d64b0-d9b0-47c4-bfb6-8333395f325a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dropdownMenu1']/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.icon-v</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>44de029d-a5bf-495d-90f9-872d6843180c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-v</value>
      <webElementGuid>ae18d74f-c68f-4ae3-833d-a9047dea9d49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropdownMenu1&quot;)/div[@class=&quot;icon-v&quot;]</value>
      <webElementGuid>8bd5419e-f254-4ded-abdd-d0239a409d61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dropdownMenu1']/div[2]</value>
      <webElementGuid>25d83cac-197d-44c5-9cc0-79c79d7bb1fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div[2]</value>
      <webElementGuid>1c360b01-8ccb-460b-ae64-5d07686dc6dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
